### ISSUE TITLE
Message "Could not parse Cryostat version string" when clicking on "About"

### ISSUE THREAD

**Issue by ahus1** [cryostatio/cryostat#1011]
I'm running the Cryostat 2.1.1 container and whenever I click on "About", I get the following error message: 

> Cryostat Version Parse Failure
Could not parse Cryostat version string 'f1810ea7'.

Instead of this message and a commit hash being displayed, I'd expect the version number of Cryostat on the About page.

![image](https://user-images.githubusercontent.com/3957921/175554472-b97021e3-50e8-44ea-9ea6-7d22d2b374e8.png)

**Comment by ebaron** [comment]
Hi @ahus1, this is a bug in our CI that we will aim to fix by our next release: https://github.com/cryostatio/cryostat/issues/966

**Comment by ahus1** [comment]
Thanks, I'll watch that ticket - feel free to close this issue.

**Comment by andrewazores** [comment]
Closed as duplicate: #966
