### ISSUE TITLE
[Task] Add aggregate information for active recordings in the GraphQL API

### ISSUE THREAD

**Issue by hareetd** [cryostatio/cryostat#1030]
In #924 the [GraphQL schema](https://github.com/cryostatio/cryostat/blob/22380ca0bd76689b3de162fb94487f1124d3775c/src/main/resources/types.graphqls#L86) for archived recordings was changed to include aggregate information alongside the actual recording list itself. 

```
type Recordings {
    active(filter: ActiveRecordingFilterInput): [ActiveRecording!]!
    archived(filter: ArchivedRecordingFilterInput): Archived!
}

...

type Archived {
    data: [ArchivedRecording!]!
    aggregate: AggregateInfo!
}

type AggregateInfo {
    count: Long!
}
```
Active recordings should mirror this change for consistency purposes. Adding more aggregate information fields alongside the count for both types of recordings would be nice as well.

**Comment by andrewazores** [comment]
Related: https://github.com/cryostatio/cryostat/issues/964
