### ISSUE TITLE
[Story] Option to automatically archive manually-created recordings on stop

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1064]
When creating a recording manually a user may specify various properties such as the data maxAge, maxSize, and the duration before the recording is automatically stopped by the target JVM.

When defining an Automated Rule a user may specify these same properties along with an archivalPeriod and a number of archived properties to preserve.

There is a middle ground option where a user may wish to create a recording manually one time for a specific profiling or troubleshooting purpose, but it's inconvenient to start the recording for a fixed duration and then have to wait around for that duration before proceeding to click the Archive button to copy the data into Cryostat's storage.

In the web-client UI there should be a checkbox or toggle like "Archive on Stop". This control should be disabled and ignored if the "Continuous" checkbox is marked. If "Archive on Stop" is marked then when the recording duration elapses, Cryostat should re-connect to the target JVM and copy the recording to archives. If the connection fails or the recording no longer exists then simply log the failure.

- [x] cryostatio/cryostat#1100
- [x] cryostatio/cryostat-web#541

**Comment by tthvo** [comment]
I think we can close this one too?

**Comment by andrewazores** [comment]
Closed, completed by #1100 and  https://github.com/cryostatio/cryostat-web/issues/541
