### ISSUE TITLE
[Task] Requests for target-specific templates return 500 instead of expected 427 on JMX credentials failure

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat#1102]
Seems like a query like `http :8181/api/v1/targets/$(echo -n service:jmx:rmi:///jndi/rmi://cryostat:9091/jmxrmi | jq -sRr @uri)/templates  "Authorization: Basic dXNlcjpwYXNzCg"` returns error code 500 if credentials are not stored, when it should probably return 427? Looks like `AbstractAuthenticatedRequestHandler` should be handling it correctly but seems like somethings off. Any thoughts @andrewazores?

_Originally posted by @maxcao13 in https://github.com/cryostatio/cryostat-web/issues/527#issuecomment-1270547462_

**Comment by andrewazores** [comment]
Ah thanks, I was just about to file this issue. I think I've found the root cause - it's pretty simple.
