### ISSUE TITLE
[Task] Split compile/container-build and itest run steps in CI

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1108]
The plain `mvn verify` invocation runs the entire build process and then the integration tests. However, the integration tests are occasionally flaky, especially in the CI environment. We should improve itest and CI reliability for one thing, but another helpful fix would be to split the build up so that the CI runner can do everything up to building the container image in one step, and then as a separate step run the integration tests using that built image. That way if the itest run is flaky the tests can simply be re-attemped using the same container image, without rebuilding.

**Comment by andrewazores** [comment]
https://maven.apache.org/surefire/maven-failsafe-plugin/examples/rerun-failing-tests.html may also be useful to include in this update

and also related: https://github.com/cryostatio/cryostat/issues/776

**Comment by maxcao13** [comment]
I want to try this, any lead to start?

**Comment by andrewazores** [comment]
Ideally this just uses `mvn` commands within `.github/workflows/ci.yaml` and runs various different tasks or build phases to split things up like I detailed originally. But, I don't think what I described is actually directly doable with just `mvn`, because it's breaking the build phases into disjointed steps run separately which is directly against Maven's usual design principle.

Right now we have something like this:

----
`ci.yaml`:
1. `mvn clean verify` <- the entire build and test process
----

But what I imagine is more like this, roughly:

----
`build-image.yaml` (dependency on existing `get-pom-properties` and `build-deps`):
1. `actions/checkout` to get the project sources
2. `mvn clean package` <- compile sources, assemble and build web-client, run unit tests, build container image
3. `podman save cryostat:latest oci-image`
4. `actions/upload-artifact oci-image` <- preserve built image for subsequent steps

`integration-tests.yaml` (dependency on `build-image`)
1. `actions/download-artifact oci-image` <- retrieve built image
2. `podman load oci-image cryostat:latest` <- restore image into this step's image registry
3. `bash repeated-integration-tests.bash` <- ideally just use `mvn` actually, but this script does what we need here by wrapping around `mvn` anyway

`spotless.yaml`
1. `actions/checkout`
2. `mvn spotless:check`

`spotbugs.yaml`
1. `actions/checkout`
2. `mvn spotbugs:check`

(this also gives a nice hook in to add something like #1133 which can `download-artifact` and then push to ghcr or quay, maybe, in the future)
----

Essentially all of this work would be done within the `.github/workflows` files. Luckily, I think that just modifying those and opening a PR of that branch will result in the modifications being what runs within that PR, so the PR is self-testing and self-verifying.
