### ISSUE TITLE
[Task] Archives incorrectly migrating

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat#1135]
To recreate:

1. Git checkout cryostat/cryostat-v2.1
2. `$ podman pull quay.io/cryostat/cryostat:2.1.0 # clear cache! `
3. `$ CRYOSTAT_IMAGE="quay.io/cryostat/cryostat:2.1.0" sh smoketest.sh`
4. create and archive a recording
5. Go back to current commit, and there will be an IOException and the recording is not migrated correctly

I think the migration is ignoring the connectUrl files.

**Comment by maxcao13** [comment]
Hmm... in theory it should work, but connecting to the target for the jvmId seems to break and result in archives becoming available for some reason.

```
WARNING: Could not get jvmId for target service:jmx:rmi:///jndi/rmi://cryostat:9093/jmxrmi
Oct 19, 2022 9:56:46 PM io.cryostat.core.log.Logger warn
WARNING: Exception thrown
io.cryostat.recordings.JvmIdHelper$JvmIdGetException: java.util.concurrent.TimeoutException
	at io.cryostat.recordings.JvmIdHelper.getJvmId(JvmIdHelper.java:137)
	at io.cryostat.recordings.RecordingArchiveHelper.lambda$migrate$0(RecordingArchiveHelper.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:979)
	at io.cryostat.recordings.RecordingArchiveHelper.migrate(RecordingArchiveHelper.java:214)
	at io.cryostat.recordings.RecordingMetadataManager.lambda$start$7(RecordingMetadataManager.java:389)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at io.cryostat.recordings.JvmIdHelper.getJvmId(JvmIdHelper.java:134)
	... 8 more

Oct 19, 2022 9:56:46 PM io.cryostat.core.log.Logger info
INFO: Successfully migrated archives
```

**Comment by maxcao13** [comment]
I'm thinking of just moving the files which cannot be migrated to some folder like `archives/temp` or `archives/lost` since if the target could not be connected to, it means likely that the target restarted or is offline and won't have the same serviceUrl any longer. Then users in OpenShift after the migration would be able to find what they've lost in this folder from the All-Archives view. There probably isn't a need to retry the connection or anything, and this would need to be documented. Thoughts? @andrewazores

**Comment by andrewazores** [comment]
I haven't reviewed the code, but just from your original description, your this is what I think *should* be happening:

When we come back online we should check the archives. Scan for those connectUrl files and check if those are connectable (in parallel). If so then check the JVM ID and transfer if it's changed. If they are not connectable then do nothing, it should appear in the All Archives view.

For pre-2.2.0 archive migrations we would expect the directories to have the service URL instead of the JVM ID as the subdirectory name, right? So if we find those then we should try to connect and get the JVM ID, then transfer the files. If we can't connect then we move the files into `archives/lost`.

Does that all make sense?

**Comment by maxcao13** [comment]
> I haven't reviewed the code, but just from your original description, your this is what I think _should_ be happening:
> 
> When we come back online we should check the archives. Scan for those connectUrl files and check if those are connectable (in parallel). If so then check the JVM ID and transfer if it's changed. If they are not connectable then do nothing, it should appear in the All Archives view.
> 
> For pre-2.2.0 archive migrations we would expect the directories to have the service URL instead of the JVM ID as the subdirectory name, right? So if we find those then we should try to connect and get the JVM ID, then transfer the files. If we can't connect then we move the files into `archives/lost`.
> 
> Does that all make sense?

Right, that was what I was thinking as well. Will start then.
