### ISSUE TITLE
[Bug] Adding JMX Credentials after Automated Rule is added/enabled forces re-activation

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1288]
## Current Behavior:
Creating a new rule or enabling an existing rule causes recording start and archival to begin. Adding new JMX credentials that apply to the same set of targets causes the rule to trigger against those targets and begin working now that the JMX connection can be established. Deactivating the rule should cause all archival tasks against all targets to stop, but at least some of them continue.

## Expected Behavior:
Disabling the rule causes all of the archival tasks to stop for all targets.

## Steps To Reproduce:
1. sh smoketest.sh
2. Delete any credentials that apply to `es.andrewazor.demo.Main` sample targets
3. Create the rule below
4. Wait a bit and observe that the rule only caused a recording to start and archivals to occur on the `9093` instance
5. Add JMX credentials in the Security view, with the same `matchExpression` as below
6. Wait a bit again and observe that now, all three target instances have the expected recording and archives are being created/deleted
7. Go back to Automated Rules table and disable the rule
8. Wait a bit again and observe that archive creation/deletion is still occurring

```json
{
  "name": "fib_rapid",
  "description": "",
  "matchExpression": "target.alias == 'es.andrewazor.demo.Main'",
  "eventSpecifier": "template=Profiling,type=TARGET",
  "archivalPeriodSeconds": 10,
  "initialDelaySeconds": 10,
  "preservedArchives": 2,
  "maxAgeSeconds": 12,
  "maxSizeBytes": 0,
  "enabled": false
}
```

## Anything else:
Related https://github.com/cryostatio/cryostat/issues/1283

**Comment by maxcao13** [comment]
Interestingly, this only happens if you specify "Clean" when stopping the rule. Another thing I noticed was that the preserved archives is actually preserving 4 archives, even though it specifies 2...
