### ISSUE TITLE
[Task] Policies for pruning target-specific uploads

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1306]
When JFR files are uploaded to the target-specific archives location, there should be some kind of policy definition that Cryostat evaluates each time a file is uploaded and causes one or more previously uploaded files to be deleted in FIFO order. The policy could consider factors such as a maximum number of files, or maximum combined size on disk, or maximum age (time since file creation).

These policies would mostly be applicable for files uploaded by Agents, but could be applied broadly.

How should these policies be defined? As a global Cryostat configuration? As a resource definition akin to Automated Rules with a matchExpression? As a request parameter specified by the client (Agent) performing the latest upload?

**Comment by maxcao13** [comment]
About this, I think having some sort of Automated Rule - like configuration json files would make sense to apply to each target, and having a default global configuration set by env vars or web-client settings at the same time also makes sense. Then the config files would override any matching targets and if multiple config files match the same target, there can be some sort of ordering that the user can apply as well maybe?

**Comment by andrewazores** [comment]
That would be very powerful, but it's also complex. Somewhat complex to implement but also complex for a user to figure out what they're actually building out of their policies. I think let's start somewhere more basic with only one layer of policies, and if there is user demand in the future for a layered approach then it can be implemented later.

Maybe let's tackle it by listing out pros and cons.

Method 1: Policy definition (akin to Automated Rules)
pros:
- dynamic at runtime, user does not need to restart Cryostat to change policies
- different policies can be applied for different targets or classes of targets
- can build a nice UI for them using features already present and planned from Automated Rules and JMX Credentials
cons:
- necessitates evaluation of policies' (at least one of them, possibly all of them) matchExpressions each time a file is pushed, can become expensive since they may need to be loaded from disk/db and the json engine needs to be run

Method 2: Startup Configuration ie env vars
pros:
- simple to implement, simple to understand
- cheap to apply when files are pushed since the behaviour is hardcoded and only a small number of primitive parameters can be varied (and don't vary at runtime)
- can build a readonly UI to show the user what the current policies are and include instructions for how to modify them by setting env vars and restarting
cons:
- inflexible, requires redeployment to modify
- inflexible for different targets or classes of targets, same policy applies to all. This is particularly relevant and restrictive for the multitenant Cryostat story.

Method 3: Client-driven policy. Client that is pushing the files also includes parameters about the policy to apply along with the file push. Limits can be supplied by env vars like in method 2, so that pushing clients can say "keep only 10 of my pushes" when the global policy is "nobody can push more than 50".
pros:
- simple to understand, simple to implement
- flexible for different targets and classes of targets since the web-client or agent are responsible for defining their own policy each time they push. Redeployment only needed if the global policy maximums are changed
- as cheap to evaluate as method 2
cons:
- UI can only be readonly. Global policy maximums can be displayed from env vars, per-target policies can be reflected by persisting just the last settings that were used to push to this target.

I think I'm most in favour of method 3. I think this feature will mostly be useful for the `cryostat-agent` when it is configured to run its JFR Harvester, which can either push on a regular schedule or push when the host target is exiting. A small number of additional config options can be added to the agent which become the policy parameters sent along with the pushed file. This way, rather than modelling the policies as a Cryostat API resource, the policies are virtually modelled by the DeploymentConfigs (in OpenShift, or some other abstraction elsewhere) that own the targets where the agents are attached.

**Comment by maxcao13** [comment]
For Method 3, let's say first a client wanted to keep 10 pushed files, and then sends 9 requests of file-uploads each with 1 JFR file. Then on the 10th, it sends a parameter that only wants to keep 1 pushed file. Would this mean that Cryostat is forced to remove the previous 9 archived files in FIFO order (not that it matters here), and then push the final uploaded file?

**Comment by andrewazores** [comment]
Correct, so long as the policy parameters accompanying each request don't exceed the global policy maximums, then Cryostat applies the current policy parameters. There is no lookback logic to only allow loosening of policies toward the global maximums, or anything like that. In your example the final 10th push would result in the previous 9 all being deleted and only the 10th remaining as the sole file. This probably just means Cryostat accepts the 10th file upload, puts it in the right storage location, and then deletes the all but the newest 1 (which ends up catching all prior 9). This could be because the user manually decided to wipe out all of those files, or perhaps because they downloaded the previous 9, manually concatenated them, and want Cryostat to replace them all with the joined file, etc. It's unlikely that this happens because of an agent configuration change since the agent's policies would be set by environment variable, and so changing the policies also entails restarting the agent, which means it should designate a new jvmId for itself.

**Comment by maxcao13** [comment]
Should there be a Queue of previously uploaded recordings per target and should these be persisted somehow, or should these file uploads be initialized empty every Cryostat run and be populated during runtime?

**Comment by andrewazores** [comment]
I imagine them being stored and handled the same way as manual uploads. Perhaps the global policies can exclude manual uploads from consideration, I'm not sure.

What kind of persisting do you mean? The existing mechanisms for storing/removing the associated metadata should trigger and persist on each upload/delete request, so between the filenames found in the filesystem and the associated metadata files the state should be queryable without even having to hold any state in memory necessarily.

**Comment by maxcao13** [comment]
I was thinking that, if we decide to exclude manual uploads from consideration, then we would have to find a way to separate them, but I guess there would be a number of ways to do that, e.g. another subfolder, adding a metadata property. I was thinking about persisting the exact upload order configuration, but I think can be done without anything extra -> what I'm doing now is just using the timestamp embedded within the recording name.

**Comment by andrewazores** [comment]
You can get the creation or modification timestamp from the filesystem attributes without embedding it into the filename:

https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#readAttributes(java.nio.file.Path,%20java.lang.Class,%20java.nio.file.LinkOption...)
