### ISSUE TITLE
[Request] Add option to run garbage collection (MemoryMXBean) 

### ISSUE THREAD

**Issue by lkonno** [cryostatio/cryostat#133]
### Describe the feature

There are several use cases that it can be useful to execute manual garbage collection (tests, memory leak investigation..). 
It can be helpful when the image does not provide the jcmd tool. 

[MemoryMXBean](https://docs.oracle.com/en/java/javase/17/docs/api/java.management/java/lang/management/MemoryMXBean.html) provides the gc() operation.

**Comment by andrewazores** [comment]
This feature is now implemented and merged in `main` and will land in 4.0. I expect it will still be a Beta feature, so users will need to go into the web-client settings and enable the Beta feature level. After that it will become available to add to the Dashboard.


https://github.com/user-attachments/assets/a8a1a12e-238a-4a36-91a0-bd2c6b5c6181
