### ISSUE TITLE
[Task] Use `xpath` if it is available in cryostat scripts

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat#1355]
> since the main cryostat image smoketest takes a bit longer with the new mvn:evaluate changes vs the old xpath.

Yea, this is unfortunate, but it's probably overall nicer that the script no longer requires `xpath` to be installed. Maybe the script should check if `xpath` is available and use it if so, falling back to `mvn:evaluate` if not.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-web/issues/842#issuecomment-1411199234_

Related to https://github.com/cryostatio/cryostat/pull/1249

**Comment by andrewazores** [comment]
Maybe the order of preference should be xpath > mvnd > mvn. Check for each of those on `$PATH` and use the first one available for reading the values from `pom.xml`. It's a little messy because the syntax for the whole command is different between `xpath` and `mvn(d)`, but maybe there is a cleaner way to do it than having an `if/else` for every time a `pom.xml` property is read.

**Comment by maxcao13** [comment]
> Maybe the order of preference should be xpath > mvnd > mvn. Check for each of those on `$PATH` and use the first one available for reading the values from `pom.xml`. It's a little messy because the syntax for the whole command is different between `xpath` and `mvn(d)`, but maybe there is a cleaner way to do it than having an `if/else` for every time a `pom.xml` property is read.

Does `mvnd` command syntax work like `mvn` ? For example, we can do ` mvnd help:evaluate -o -B -q -DforceStdout -Dexpression="$1"` ? Then wouldn't overriding the envvar `MVN=mvnd` work? Assuming it works this way anyways.

**Comment by andrewazores** [comment]
Yes, `mvnd` is generally a drop-in replacement for `mvn`:

```bash
mvnd -Dmvnd.rawStreams $@
```

This line from the `~/bin/mvn` script I shared means that what I'm normally doing in my shell is typing ex. `mvn clean package`, which actually invokes the `~/bin/mvn` script with the `[clean, package]` args. The script then forks a `mvnd` process with the args `[-Dmvnd.rawStreams, clean, package]`. Without the `rawStreams` property `mvnd` tags the log output with `stdout`/`stderr` which breaks some other scripting, so adding that property means the output format is also identical to standard `mvn`.

> Then would overriding the envvar MVN=mvnd work?

This is actually why I've put that `MVN=/usr/bin/mvn` overrideable variable into a bunch of the scripts, it's a holdover from when I was first experimenting with `mvnd` and wanted to be able to do ex. `MVN=~/bin/mvnd sh smoketest.sh` or whatever.
