### ISSUE TITLE
[Task] Implement JVM details endpoint over JMX 

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat#1360]
## Describe the feature
Related https://github.com/cryostatio/cryostat-web/issues/865

> https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html
> 
> https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryMXBean.html
> 
> https://docs.oracle.com/javase/8/docs/api/java/lang/management/RuntimeMXBean.html
> 
> https://docs.oracle.com/javase/8/docs/api/java/lang/management/ThreadMXBean.html
> 
> The backend side would simply be an API endpoint (and/or GraphQL fetcher) that clients can request various details from a target. Initially only over JMX but this could be expanded to over HTTP via the cryostat-agent in the future as well. By including HTTP query parameters or specifying fields in GraphQL, the client can request various details which get mapped by the server into remote requests to the target, and the returned values bundled up into an HTTP API JSON response to the client. I think the data would simply be pulled on demand and as a first pass with no particular caching strategy and no persistence.

**Comment by maxcao13** [comment]
Just so I'm not missing something, this require `-core` to be updated with new methods that invoke the various MXBeans within the `JFRConnection` class, right?

**Comment by andrewazores** [comment]
Yes, that sounds right.
