### ISSUE TITLE
[Story] Docker API discovery

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1439]
There is already an internal discovery client for the Podman REST API (libpod):

https://github.com/cryostatio/cryostat/blob/main/src/main/java/io/cryostat/platform/internal/PodmanPlatformClient.java

The Docker Engine has a very similar API. It would be good if Cryostat also had an internal discovery client for this case.

https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerList

**Comment by ishridharhegde** [comment]
Hi @andrewazores, I would like to work on this.
Can you assign this to me?
