### ISSUE TITLE
[Bug] Cryostat keeps failing with "Too many open files", exhausts descriptors

### ISSUE THREAD

**Issue by akevdmeer** [cryostatio/cryostat#1444]
## Current Behavior:
Cryostat keeps failing with "Too many open files" as it exhausts its descriptors opening and keeping open the directories `/opt/cryostat.d/recordings.d/*`. Looking in /proc/pid/fd of the current process, it has each such directory open more than 10.000 times.

## Expected Behavior:
Cryostat should not exhaust its descriptors keeping directories open many times over.

## Environment:
- OS: Fedora CoreOS 37
- Environment: Vanilla Kubernetes
- Version 2.2.1
-

**Comment by andrewazores** [comment]
@akevdmeer thanks for the report, I'll look into this today.

**Comment by andrewazores** [comment]
@akevdmeer would you be able to share the Cryostat container logs when this occurred?
