### ISSUE TITLE
[Bug] Logout failure on OCP 4.12+

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1489]
## Current Behavior:
Clicking the Logout button in the Cryostat Web application fails when Cryostat is deployed on OCP 4.12, 4.13. In 4.11 it works as expected.

## Expected Behavior:
Clicking the Logout button should result in the user being redirected to the cluster OAuth login on all OCP versions.

The following message appears in the browser dev console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://oauth-openshift.apps-crc.testing/logout. (Reason: CORS header 'Access-Control-Allow-Origin' missing). Status code: 200.
```

This may be a bug with the OpenShiftAuthManager implementation in the Cryostat backend (this repo), or it may be a bug in how the Cryostat Operator sets up the oauth-client. I don't think this is actually related to the Cryostat Web application.

Potentially related:
- [ ] https://github.com/cryostatio/cryostat-operator/issues/583
- [ ] https://github.com/cryostatio/cryostat-operator/issues/579

**Comment by ebaron** [comment]
I haven't been able to find what's changed between 4.11 and 4.12 that's affected this. It seems as though there's no special handling for the OpenShift Console though.

> The OpenShift Console handles the same flow this way:
> 
> https://github.com/openshift/console/blob/3e0bb0928ce09030bc3340c9639b2a1df9e0a007/frontend/public/module/auth.js#L100

If we were to implement logging out the same way as the console, could we avoid adding the Cryostat route to the API Server's `additionalCORSAllowedOrigins` (which seems to no longer be working for us)? If so, that would be by far the better approach.

**Comment by andrewazores** [comment]
I think we can do this relatively easily. We just need to rework our [logout endpoint](https://github.com/cryostatio/cryostat/blob/3f191a739d353d417cfd2c206c6852f1a2659917/src/main/java/io/cryostat/net/web/http/api/v2/LogoutPostHandler.java#L102) somewhat so that it provides more ability to act as a proxy to the OpenShift auth server for the web-client, and then our web-client can basically just implement the same things we see the OpenShift Console doing for its logout flow.

**Comment by andrewazores** [comment]
Maybe we can actually just augment the Cryostat `OpenShiftAuthManager` login/logout flow to behave that same way that the OpenShift Console does and perform these requests on our server, rather than our (web)client. From a quick glance it looks like that should probably work, which makes the change smaller and easier to manage if so. This also means that the OpenShift-specific behaviour can be contained on the already-OpenShift-specific auth code in the server, so our web-client can remain platform agnostic.
