### ISSUE TITLE
[Bug] Resource limits are too low for smoketest

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat#1629]
### Current Behavior

              > I am experiencing some thread blocks while running smoketest. Does this have something to do with container resource constraints?
> 
> https://gist.github.com/tthvo/19ef7e7f9a2c12c974f6710cebb9fdde

These particular thread blocks you're seeing are happening on startup, so perhaps there is something that can be done to move those startup tasks onto worker threads instead of the main Vertx event loop, but I'm not sure.

In any case, this probably highlights that the limits we set are too low and cause performance issues.

> Looks like setting `--memory` is actually configuring the memory/cpu limit, not a request.
> 
> ```shell
> -m, --memory <number>[<unit>]                  Memory limit (format: <number>[<unit>], where unit = b (bytes), k (kibibytes), m (mebibytes), or g (gibibytes))
>       --memory-reservation <number>[<unit>]      Memory soft limit (format: <number>[<unit>], where unit = b (bytes), k (kibibytes), m (mebibytes), or g (gibibytes))
> --cpus float                               Number of CPUs. The default is 0.000 which means no limit
> ```
> 
> I think the table here suggested the request resources only, not limits. https://github.com/cryostatio/cryostat-operator/blob/main/docs/config.md#resource-requirement

It's true, but if I understand the requests/limits mechanisms correctly, the requests are used for scheduling containers/Pods onto nodes to ensure that at least that amount of resource is available. So if these are the default requests we set then it should result in a Cryostat deployment that runs reasonably well with only those resources, since there is no guarantee there are actually any more resources than that. Of course, not every resource is actually equivalent across different hardware - perhaps the memory usage is different between amd64 and amd64 for example, and certainly CPU time means different things when running on different kinds of CPU.

Basically, the point here is to make `smoketest.sh` simulate the worst-case scenario for an Operator deployment, so we can make sure we aren't only seeing that things run well when the Cryostat deployment is allowed to use a whole machine's worth of resources, but that it can still run well with some reasonable resource constraints that allow it to run with reasonable and justifiable cost in real deployments.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/1614#issuecomment-1690016286_
            

### Expected Behavior

The limit should allow the smoketest to run without issue, at least.

> The container limits on smoketest.sh/run.sh and the corresponding default requests set by the Operator (and -helm?) should be investigated and probably increased then.

### Steps To Reproduce

Run `sh.smoketest.sh` and see thread block issues.

Since https://github.com/cryostatio/cryostat/pull/1615

**Comment by andrewazores** [comment]
Any proposed change of value should be tested at minimum in the `smoketest.sh`/`run.sh` setups as well as in OpenShift Local (`crc`) on the same machine, as well as ideally on some other OpenShift cluster on other hardware.

**Comment by andrewazores** [comment]
@mwangggg or @aali309 any interest?
