### ISSUE TITLE
[Bug] `/request_review` PR workflow runs fail due to apparent permissions issue

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1654]
Didn't work:

https://github.com/cryostatio/cryostat/actions/runs/6087853970/job/16517292637

```
 Adding label 'review-requested' to the PR
https://github.com/cryostatio/cryostat/pull/1636
Requesting review from @cryostatio/reviewers
error fetching organization teams: GraphQL: Resource not accessible by integration (organization.teams)
Error: Process completed with exit code 1.
```

I checked the organization settings and it looks like the reviewers team is publicly readable, so I think this workflow might need to run with some elevated token permissions?

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/1638#issuecomment-1707029937_

**Comment by andrewazores** [comment]
- https://github.com/orgs/skills/discussions/150
- https://stackoverflow.com/questions/75807486/github-cli-command-gh-failing-to-create-repository
- https://dev.to/callmekatootie/debug-resource-not-accessible-by-integration-error-when-working-with-githubs-graphql-endpoint-5bim

**Comment by tthvo** [comment]
Also, need to upgrade to checkout@v4 here. 

https://github.com/cryostatio/cryostat/blob/92fdae565c8530cef7a5d3fdd8fce096b442770f/.github/workflows/pr-remove-request-review.yml#L17

Seems like we need the checkout action to cache the credentials: https://github.com/actions/checkout#checkout-v4

I think we can just set up the environment for `gh` cli like this: https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows

**Comment by tthvo** [comment]
Unfortunately, there is no `org:read` for `GITHUB_TOKEN`:

- https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
- https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#about-teams

How about either:
- Only add the `request_review` label and reviewers can manually filter PRs to check.
- Use PAT to have access to team features.
- Or just requests reviews from all members of the team explicitly. We can centralize it with some configuration file hosted somewhere, for example: https://github.com/marketplace/actions/auto-request-review

What do u think?

**Comment by andrewazores** [comment]
1. would be okay, but part of why assigning a reviewer is helpful is because it generates a GitHub notification to call attention to the PR
2. moving away from using a PAT is ideal but if there are things only working when using one, perhaps we just stick to it for those cases. At least the permissions scope is reduced to only a few things.
3. that could also work but it means that we would be duplicating the team definition, or else completely replacing the team definition with the config file. I think I'd rather have the team definition be part of the org settings rather than a config file that is tracked as part of the project sources.

**Comment by andrewazores** [comment]
The label removal also fails: https://github.com/cryostatio/cryostat/actions/runs/6099434719/job/16551575079?pr=1636

**Comment by andrewazores** [comment]
https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac

**Comment by tthvo** [comment]
Looks like the event `pull_request_review` is not a priviledged event.

![image](https://github.com/cryostatio/cryostat/assets/68053619/bc9dc0b7-9e1d-49e7-a642-1ecaddf7fefc)

**Comment by tthvo** [comment]
Can we use mergify?

https://docs.mergify.com/actions/request_reviews/

https://docs.mergify.com/actions/label/

**Comment by andrewazores** [comment]
I guess we can chain the Workflow and Mergify. When a user comments `/request_review` the Workflow adds the `review-requested` label, and when Mergify sees this label it assigns the team as reviewer? Sounds alright.

**Comment by andrewazores** [comment]
Ah I see that's what you're already working on in your draft PR :)

**Comment by tthvo** [comment]
Right exactly! The removal might be troublesome :)) Not sure how to control Mergify for that but looking into it...
