### ISSUE TITLE
[Bug] "Restart if recording already exists" checkbox doesn't work

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1670]
### Current Behavior

Creating a recording with name Foo, then trying to create another recording with name Foo, does fails with an HTTP 400.

### Expected Behavior

The request should fail if the "restart" checkbox is not checked, but should pass and result in the recording being restarted if the box is checked.

### Steps To Reproduce

1. Run sh smoketest.sh
2. Go to web UI
3. Go to Recordings
4. Select a target, etc. `vertx-fib-demo-1`
5. Create a recording manually, ex. named `test`, continuous duration, Continuous template
6. Try to repeat step 5 with and without the "restart" checkbox checked

### Anything else?

![image](https://github.com/cryostatio/cryostat/assets/3787464/ad0a7153-3b7f-4b86-8290-1ebdde2e7491)

**Comment by tthvo** [comment]
Looks like we are ignoring the `restart` parameter here and the replace policy will return as NEVER?

https://github.com/cryostatio/cryostat/blob/0197f7b20ca9a90c0831e4936b95c04108378afc/src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandler.java#L156

**Comment by tthvo** [comment]
This is call from web client: https://github.com/cryostatio/cryostat-web/blob/ee99ad168f707e4342444589a466f9abb0ca6599/src/app/Shared/Services/Api.service.tsx#L308

**Comment by andrewazores** [comment]
Right -

https://github.com/cryostatio/cryostat/pull/1587

https://github.com/cryostatio/cryostat/pull/1587/files#diff-52b7be8bc2188ea065259592ef8710555d3d73dabd58cd2ce0b3a57ab4c6f999L155

I recall we had some discussion around this change before but I can't remember exactly what we landed on. Since this is changing in a minor release version the API "shouldn't" change in incompatible ways, but I'm okay with changing a query parameter like this. Or we could have the endpoint handler handle both forms and prefer the newer one if both are supplied.

**Comment by andrewazores** [comment]
ie.

```
ReplacementPolicy replace = ReplacementPolicy.NEVER;
if (attrs.contains("restart")) {
  replace = Boolean.parseBoolean(attrs.get("restart")) ? ReplacementPolicy.ALWAYS : ReplacementPolicy.NEVER;
}
if (attrs.contains("replace")) {
  replace = ReplacementPolicy.fromString(attrs.get("replace"));
}
}
```

**Comment by tthvo** [comment]
This one looks good! I can help apply above fixes.
