### ISSUE TITLE
[Task] Comment-triggered workflows should report status checks

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1734]
Nice, it passed - would be even nicer if the status got reported, either as a comment again like we already have elsewhere, or [as a status check item](https://josh-ops.com/posts/using-github-checks-api/)

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-core/issues/279#issuecomment-1772740122_

**Comment by mwangggg** [comment]
already [done](https://github.com/cryostatio/cryostat3/blob/d42a2c29f8ff115d4554ecf5970bc898732bd166/.github/workflows/pr-ci.yaml#L177-L183) for 3.0, won't do for 2.x
