### ISSUE TITLE
[Bug] Archives > All Archives > Download does not download JFR file

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1738]
### Current Behavior

Since #1692 / #1731 , attempting to download archived recording from the All Archives view partially fails - the JSON metadata file is downloaded, but the actual JFR binary is not.

### Expected Behavior

Both the metadata JSON and the JFR binary should be downloaded to the local workstation filesystem.

### Steps To Reproduce

1. Ensure clean state: `rm -rf conf/h2* conf/postgres archive/* conf/metadata conf/probes.d conf/rules`
2. Check out latest `main` or latest `cryostat-v2.4` upstream branches, `./mvnw clean package ; podman image prune -f`
3. Run `sh smoketest.sh`
4. Select a target, ex. `localhost:0` (Cryostat itself)
5. Create a flight recording, give it at least a few seconds, then archive it
6. Go to Archives view, select All Archives tab. Expand the table row for `localhost:0`, click the overflow menu on the recording item, and attempt to download it
7. Observe what gets downloaded. There should be both a `.jfr` and a `.metadata.json`

### Environment

```Markdown
- Version: 2.4.0-snapshot, 2.5.0-snapshot
```

**Comment by andrewazores** [comment]
Hang on, let me re-test this. It occurs to me that maybe the problem was my testing setup - I used the CI-built test image that should have included the correct frontend changes, but maybe that didn't work and the problem is actually the mismatch of versions.

**Comment by andrewazores** [comment]
No, I don't think that was it - I can still reproduce the failure with a hand-built test image.

**Comment by mwangggg** [comment]
I just tested without the frontend changes from https://github.com/cryostatio/cryostat-web/pull/1127 and I am able to download both the jfr and the metadata json. I will test with the frontend changes and see if the jfr file isn't being downloaded?

**Comment by mwangggg** [comment]
even when I run with the CI-built test image or by running `yarn start:dev`, I see both files being downloaded

**Comment by andrewazores** [comment]
Hmm. Make sure to try a hard-refresh in your browser as well (probably ctrl+shift+r) to make sure that your browser isn't reusing a cached version of the web-client. We have stuff in the web build process that should cachebust when the client is rebuilt but it doesn't seem to always work as intended.

I'll also try to reproduce this again to verify it's real.

**Comment by mwangggg** [comment]
I used the `CRYOSTAT_IMAGE=ghcr.io/cryostatio/cryostat-web:pr-1127-41c6eeb8817efb52e625a803edf6ceffbd19196d sh smoketest.sh` command and hard-refreshed my browser and it's still downloading both files:
![Screenshot from 2023-10-23 15-58-44](https://github.com/cryostatio/cryostat/assets/90855268/4e182f5d-86b0-43a4-9a27-a771672546ac)

**Comment by andrewazores** [comment]
Huh, trying it again now it seems to work with the CI-built image for me as well. I'll close this issue then and reopen it in case the issue reappears.

**Comment by tthvo** [comment]
Sorry I am seeing the same issue when building the image from latest main.

![image](https://github.com/cryostatio/cryostat/assets/68053619/b7ce05d3-319c-45a8-a524-75b7f6b745bc)

**Comment by andrewazores** [comment]
^ @tthvo did you check out cryostatio/cryostat-web#1127 along with that build?

**Comment by tthvo** [comment]
Yehh I tried with the image @mwangggg sent above.

![image](https://github.com/cryostatio/cryostat/assets/68053619/41a2d7ef-86d6-4ef6-bc89-e975b376d67a)

**Comment by andrewazores** [comment]
Bah. Trying it once again now and I'm also seeing the `.jfr` download failure too.

**Comment by tthvo** [comment]
Logs are not that very helpful haha

```
WARNING: 10.0.2.100 - - [Mon, 23 Oct 2023 20:55:50 GMT] 2ms "GET /api/beta/fs/recordings/LBAWISRZJVBVCTRYNBVDOZSZIFXGQ2DXIFXFQNTOMM4UGMS2IRJEQU2GMRWGCZJVGNCTQPI=/es-andrewazor-demo-Main_test1_20231023T203544Z.jfr/jwt?token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..h6dIg2T14O9fC52w.FECthc2_O3HqU8ff2OwGtc18Xh67X_XuWt_4EqOQQ1ZLk_Xg81UODvx7eaCExkPTpCXTXh6hpfkFuyaT6Dci0rbg_mDvUrwKZVfL4GiDFp1_RUCbeJ_M00lwVXMJUq4kmbFws_sXwXVtgrfN4k7jfMY9RvGeAsTRQckID4FL6HOdIOyoi1453BiAI2bLvp3Mmic65y1v_Dktgtf1C2lr18PzDQpajcnPdJy85Oj21osUbDqJziAGMw3xM2FFj2-ufpXcfc_YYurvFN_MBkZ_u7wJfP-yQSH5w6lU3zRITFRHRDgxg2B9vHpfmVybIe5LA1cjYpke9EOHo59DGJPcGdMKBMSnOSish5dJUkj3Ly5GP8M82Jnw-eZakQ_kBLq1OlruG6mfL2PlsoWwjz38wU_gLMesVf59Me8y6_MoIckvQQ5SVjqvd03ZLt31raL4OMkX2k2X78ghCTJj5ABeH8s9Fs3UHc-2EZ99y6Bg94CZ78Rda1AN7V_qD9uRzpbSOwr03bsvOs4FpysfbMZa77QmWkS6P0xKTtjn_VuyB28LVsZCKGgfj5Lr8mjarTo84nqvE1gxq7OQgOJyWPM3vy6ZJMVdq3KY2BnlB7Xmk5IbcWUsRRzS6GC-Ic5fL15Lp6aR_Yfl_jK0L1Rt4qiHi_TMEeP28rk.a_uV191Unl0c_XDBMm-4IA HTTP/1.1" 404 340 bytes "https://localhost:8181/archives?tab=all-archives" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
```

**Comment by mwangggg** [comment]
just tried again and I still can't reproduce this issue :confused:

**Comment by andrewazores** [comment]
Using the same CI image as before, I just reproduced it now. Maybe let's try the exact same setup and see if we can narrow down where the differences come in.

![image](https://github.com/cryostatio/cryostat/assets/3787464/23be8f5a-91e3-46f4-a4ab-e937aa45cfc6)

- `rm -rf conf/h2* conf/postgres archive/* conf/metadata conf/probes.d conf/rules` to ensure clean state/no existing archives
- Select JMX target `cryostat:9093` `vertx-fib-demo` as discovered by JDP
- Created a 30 second Profiling recording named `test`, let it archive on stop
- Go to Archives > All Archives and try to download it

![image](https://github.com/cryostatio/cryostat/assets/3787464/b980419d-b306-4ebc-a82d-2e755b2fe48b)

![Screenshot_2023-10-24_09-58-03](https://github.com/cryostatio/cryostat/assets/3787464/7e8355e2-4efb-4c1c-b68c-9f6c988cfe6d)

**Comment by mwangggg** [comment]
With the exact same steps on my computer, I still see the jfr file :confused: I'm trying in incognito right now.

**Comment by tthvo** [comment]
@mwangggg Did u try downloading when in the `All Archives` tab?

**Comment by mwangggg** [comment]
oh my god
