### ISSUE TITLE
[Bug] CI does not have permissions to download `cryostat-core` dependency

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1796]
Workflow started at 11/28/2023, 10:18:13 AM. [View Actions Run](https://github.com/cryostatio/cryostat/actions/runs/7020847064).

_Originally posted by @github-actions[bot] in https://github.com/cryostatio/cryostat/issues/1795#issuecomment-1830056454_

**Comment by andrewazores** [comment]
I suppose this is related to my recent org-level change to read-only-by-default secrets, though I'm not sure exactly how since this looks like it's only trying to read an artifact from the GitHub Maven Packages repository. But I don't think anything else has recently changed that would affect this.

@aali309 @mwangggg could one of you take a look?

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/actions/runs/7021086038

**Comment by andrewazores** [comment]
Interestingly, it looks like the backport of the same PR above got past that stage:

https://github.com/cryostatio/cryostat/actions/runs/7021108433

**Comment by mwangggg** [comment]
Although it looks like it, it's not a permissions problem- it's an error with the way we're caching the maven files. I'm not quite sure what's wrong with the `skjolber/maven-cache-github-action@v1` action, but it just doesn't properly cache the files. I updated the workflows to use `actions/cache@v3` instead and it seems to be getting past this error :grin:

**Comment by andrewazores** [comment]
I'll just tag this one here as well since I think it may actually be the original issue I thought I was reporting here :)

https://github.com/cryostatio/cryostat-core/actions/runs/7052673314

from https://github.com/cryostatio/cryostat-core/pull/309
