### ISSUE TITLE
Notifications on all "state" changes

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#354]
All backend "state" changes (not all of these are truly backend state, but some kind of action on a target) should all be indicated by an event on the Notifications channel so that other client instances are informed of the changes without having to poll.

Examples:
1. Active recording created/deleted
2. Active recording archived
3. Archived recording created/deleted
4. Event template uploaded/deleted

**Comment by jan-law** [comment]
The corresponding frontend issue is closed (https://github.com/cryostatio/cryostat-web/issues/165). Can this issue be closed too?

**Comment by andrewazores** [comment]
Yes, I think so. Thanks.
