### ISSUE TITLE
Tree view for Targets

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#421]
It may make sense to add/replace the current flat list of targets/ServiceRefs with a hierarchical structure to represent the complete landscape that ContainerJFR can see when it is deployed. For example, when deployed in OpenShift/Kubernetes, this could mean the Deployment, Pods and Replicas, Containers/Endpoints. The UI could render this as an interactive tree view and users could perform batch operations on all targets within a Pod by selecting the Pod node, for example, or drill down and perform an operation on a single JVM target by selecting the Endpoint.

**Comment by Alexjsenn** [comment]
In terms of the data structure that should be created and maintained by the platform client, I was thinking of something like a custom tree.

```
public class Object {
    private String name;
    private List<Object> children;
    private List<String> labels;
}
```
Another possibility would be to have a map for the children, but what I am not sure about is what keys to use (names makes sense but is likely not unique).
In the case of Openshift and Kubernetes it might be ideal to have a pointer to the actual object, such as deployment or pod, or it may not be, but I'm not sure if that could be generecized as you suggested. 
This structure can then be sent to the web client to produce a visualization, as well as to allow for group operations on endpoints.

**Comment by andrewazores** [comment]
I do think a tree is the right data structure for this kind of hierarchy. Your proposed node type structure there looks like it's on the right track.

What I roughly had in mind, in JSON(ish) notation, would be something like this for OpenShift/Kubernetes:

```
{
    "nodeType": "Namespace",
    "labels": [
        {
            "key": "name",
            "value": "mynamespace"
        }
    ],
    "children": [
        {
            "nodeType": "Deployment",
            "labels": [
                {
                    "key": "name",
                    "value": "sample-app-deployment", 
                },
                {
                    "key": "app",
                    "value": "sample-app"
                }
            ],
            "children": [
                {
                    "nodeType": "Pod",
                    "labels": [
                        {
                            "key": "name",
                            "value": "sample-app-abc123",
                        },
                        {
                            "key": "app",
                            "value": "sample-app"
                        }
                    ],
                    "children": [
                        { 
                            "nodeType": "Container",
                            labels: [
                                {
                                    "key": "name",
                                    "value": "sample-app-jvm",
                                },
                                {
                                    "key": "app",
                                    "value": "sample-app"
                                }
                            ],
                            "serviceRef": {
                                "jmxUrl": "service:jmx:rmi://localhost:9091/jndi/rmi://fooHost:9091/jmxrmi",
                                "alias": "SampleApp"
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```

In a Podman deployment, the data would have the same general form but perhaps with fewer layers of hierarchy, ex.:

```
{
    "nodeType": "Network",
    "labels": [
        {
            "key": "name",
            "value": "test-network"
        }
    ],
    "children": [
        {
            "nodeType": "Pod",
            "labels": [
                {
                    "key": "name",
                    "value": "app-pod", 
                }
            ],
            "children": [
                {
                    "nodeType": "Container",
                    "labels": [
                        {
                            "key": "name",
                            "value": "webserver",
                        }
                    ],
                    "serviceRef": {
                        "jmxUrl": "service:jmx:rmi://localhost:9091/jndi/rmi://fooHost:9091/jmxrmi",
                        "alias": "WebServer"
                    }
                }
            ]
        }
    ]
}
```

I have used `Container` as the `nodeType` of the leaf nodes in this tree rather than `Endpoint` because IMO, Endpoint is just an OpenShift/Kubernetes implementation detail that we're currently using to concretely locate what are still logically/conceptually containers.

**Comment by ebaron** [comment]
Do we plan for this to have a corresponding HTTP API to support these kind of batch operations?
Something like:
`POST /api/v2/deployments/:deploymentName/recordings/`

**Comment by andrewazores** [comment]
Something like that, perhaps. It will be exposed through the HTTP API of course, but I don't really want to create a whole mirrored hierarchy of API endpoints and handlers for them.

I haven't thought very deeply about this, but our other discussion about ServiceRefs/targetIds seems relevant (https://github.com/cryostatio/cryostat-operator/issues/205#issuecomment-849960340).

I'm thinking that if we can implement something within Cryostat to assign a unique ID to ServiceRefs and use those IDs to reference them, rather than using the JMX Service URL as the ID, then we could also assign unique IDs to things like Deployments or Pods or Namespaces. The client could then make a request to the existing API endpoint like `POST /api/v1/targets/abc123/recordings`, where `targetId=abc123` actually denotes ex. a Deployment object. The API handler would have some internal registry that knows how to map a targetId to a set of ServiceRefs, which may be a simple singleton set if the client is performing an operation on a single target or may be an arbitrarily large set otherwise, and then the handler would perform its usual remote operation upon each such ServiceRef.

**Comment by ebaron** [comment]
One part I'm unclear about with this approach is how the client discovers the target ID for a Deployment/ReplicaSet/Pod. If I want to create a recording for Deployment _foo_, how do I find out the target ID to pass to the HTTP request? I could query the `/api/v1/targets/` endpoint, but then I'd have to look through them all to find the Deployment named _foo_.

**Comment by andrewazores** [comment]
I think for that case we would look to add query parameter support to `GET /api/v1/targets` and others like it, so the client could do something like `GET /api/v1/targets?type=Deployment&name=foo`.
