### ISSUE TITLE
API exception responses should contain more detail

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#435]
https://github.com/rh-jmc-team/container-jfr/pull/423#issuecomment-819553853

**Comment by jan-law** [comment]
@andrewazores a few questions before I get started:

I noticed the specific `IOException` referenced in the above comment was from the `autorules` branch. What is `autorules` for? Which branch does this issue apply to?

What is the purpose of adding more detail to the API exception responses? How can I determine which API exception responses require more detail?

**Comment by andrewazores** [comment]
> @andrewazores a few questions before I get started:
> 
> I noticed the specific `IOException` referenced in the above comment was from the `autorules` branch. What is `autorules` for? Which branch does this issue apply to?

The `autorules` branch is a semi-long-lived upstream branch which is tracking the implementation of a larger feature (#355). Because that feature is quite large and involves several distinct sub-features, it's being worked on as an upstream feature branch, to which follow-up PRs are made to incrementally implement the overall feature. When all of the sub-features are complete the `autorules` branch will be merged into `main` and deleted.

This issue (#435) applies to `main`, and ideally a solution here will automatically apply to `autorules` as well (ex. by inheritance/composition or some other technique that makes the solution generic, and not implemented in each API handler).

> 
> What is the purpose of adding more detail to the API exception responses?

The purpose is to be more informative for clients when failures do occur. In the linked example we have an error that simply says `{"meta":{"type":"text/plain","status":"Internal Server Error"},"data":{"reason":"IOException occurred while writing rule definition"}}`, and a good suggestion that it might instead say something like `{"meta":{"type":"text/plain","status":"Internal Server Error"},"data":{"reason":"IOException occurred while writing rule definition: Rule with name "foo" already exists; refusing to overwrite"}}`. Currently, a client making such an incorrect request does not actually know the reason that the request failed - it may be because of a name collision, but it could by some other `IOException` too and these would all be indistinguishable. For example, the process may be lacking write permissions to the directory where rule definitions are persisted.

> How can I determine which API exception responses require more detail?

This is the key question here. If you inspect some existing handlers, you will see that in certain scenarios the handlers themselves throw very specific `HttpStatusException`s with custom messages already. In other cases, the API error response comes from an uncaught exception in the handler being later caught and handled by the `WebServer`, which gives a much more generic API response like the IOException one above.

One solution path could be to go through all handlers and ensure that every possible exception path is covered with try/catch and a rethrown `HttpStatusException` containing a more informative message, but this is a *huge* amount of busywork and not very maintainable.

A better path to start looking for a solution is to examine how the `WebServer` handles the other, non-`HttpStatus` `Exception`s, and see if there is a way to augment these API responses with more information.

**Comment by jan-law** [comment]
Thanks for your detailed answers @andrewazores. I have more follow up questions:

> examine how the `WebServer` handles the other, non-`HttpStatus` `Exception`s,

 I'm assuming you mean `ApiException` when you wrote "`non-`HttpStatus` `Exception`s`"? 
The `Webserver` error page handler only seems to check for `HttpStatusException`s, `ApiException`s, and any exceptions from `v1`. I'm also assuming we aren't making any more changes to the `v1` handler code.

> see if there is a way to augment these API responses with more information

I noticed the `WebServer` uses the `reason` string to populate `ApiErrorData`. I was considering appending `e.getMessage()` to the `reason` string somehow, either in `WebServer` or the `ApiException` constructors to match your example without editing the exceptions in each handler.
```
throw new ApiException(500, "IOException occurred while writing rule definition: " + e.getMessage(), e);
```
Except this wouldn't add any additional information for the exceptions that already use `e.getMessage()` as the `reason`, eg in
`Abstractv2RequestHandler.java` line 115
 ```
} catch (Exception e) {
           throw new ApiException(500, e.getMessage(), e);
```
For your example above, `e.getMessage()` provided enough detail to the error response. Can I assume it's enough detail for all `ApiException`s? If not, what other types of information would be useful to clients?

Also, what's the best way to test my changes?

**Comment by jan-law** [comment]
A summary of what we talked about in case I need to refer to it later:

> I'm assuming you mean ApiException when you wrote "non-HttpStatus Exceptions"?

After manually triggering a ```URISyntaxException()```, it looks like at least one of the error responses that don't give enough information (ie `Internal Server Error`) are from `HttpStatusException`s. I'll look at `TargetRecordingsPostHandler` and other handlers that might give the same error response.

> Can I assume it's enough detail for all ApiExceptions? 

We decided the `WebServer` should ideally include any error info it has (eg `cause`, `e.getMessage()`) in the error response. If the handler that threw the exception doesn't have any additional error information then it may not be worth looking for more info.

> Also, what's the best way to test my changes?

Can either test by intentionally throwing an exception in a function and then running the tests to see what kind of error message appears, or interact with the web ui and see the error messages as they appear

**Comment by andrewazores** [comment]
> Can either test by intentionally throwing an exception in a function and then running the tests to see what kind of error message appears, or interact with the web ui and see the error messages as they appear

Yep, or use curl/HTTPie to get the same data on a command line. The web client basically just takes that same data and stuffs it into a popup notification, but this way you can see the exact API response and know that it isn't being truncated or anything omitted by the UI.
