### ISSUE TITLE
View in Grafana not working with smoketest.sh

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat#483]
When running smoketest.sh, selecting "View in Grafana..." fails with a 512 error.

```
SEVERE: Exception thrown
io.vertx.ext.web.handler.impl.HttpStatusException: Server Error (512)
```
![Screenshot_2021-05-25 Recordings(1)](https://user-images.githubusercontent.com/4326090/119568166-3273a980-bd7b-11eb-8357-4ce449d43e88.png)

If I visit the JFR Datasource URL at `http://0.0.0.0:8080`, I instead see a Fibonacci demo. Perhaps there's a conflict with port numbers?
![Screenshot_2021-05-25 Fibonacci Demo](https://user-images.githubusercontent.com/4326090/119568532-87172480-bd7b-11eb-80bd-ae264832b0da.png)

**Comment by jan-law** [comment]
After setting the http port for all the vertx-fib-demos to 8081, this is what grafana looks like when I click "View in Grafana". I only see a blank screen at ```http://0.0.0.0:8080```. What should the JFR Datasource look like?
![Screenshot from 2021-05-31 10-01-10](https://user-images.githubusercontent.com/84587295/120206085-bead2300-c1f8-11eb-9f2e-53cf9ab5afc6.png)
![Screenshot from 2021-05-31 10-10-46](https://user-images.githubusercontent.com/84587295/120206082-be148c80-c1f8-11eb-9511-db3eb24f0d32.png)
![Screenshot from 2021-05-31 10-13-33](https://user-images.githubusercontent.com/84587295/120206283-00d66480-c1f9-11eb-9deb-c3f515e64d1a.png)

**Comment by ebaron** [comment]
A blank screen for JFR Datasource is expected. As long as "View in Grafana" works and there are data points shown in the dashboard called "Dashboard", then I would consider this fixed.

**Comment by andrewazores** [comment]
Yup, the `jfr-datasource` itself is just a sort of translation endpoint - you upload (POST) a .jfr file to it, and then you can query (GET) some JSON-formatted metrics that are parsed out of the JFR file. There's no UI there on its own - the Grafana dashboard does that.

From your screenshots it looks like the issue is solved @jan-law .
