### ISSUE TITLE
Auto-Rules JSON creation does not validate numeric values

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#530]
https://github.com/cryostatio/cryostat/pull/416#issuecomment-865365655

When POSTing a rule definition, all of the same validations should be performed on the input whether it is supplied as a form or a a JSON document. Currently, the JSON document pathway does not validate numeric inputs the same way that the form pathway does.

**Comment by jan-law** [comment]
Is this `Rule` constructor logic desirable? Neither the form nor JSON document pathway will inform users of negative `maxAgeSeconds` or `maxSizeBytes`:
```
this.maxAgeSeconds =
                builder.maxAgeSeconds > 0 ? builder.maxAgeSeconds : this.archivalPeriodSeconds;
this.maxSizeBytes = builder.maxSizeBytes;
```

**Comment by andrewazores** [comment]
There needs to be a way for users to specify unlimited size/age, so this could be 0 or a negative value. If the max age isn't specified but the archival period is specified then the max age is set to equal the archival period, so that the series of archived recordings contain as little overlapping data as possible.

Gson would normally deserialize a missing numeric entry as 0 here anyway, so a negative value would mean the client explicitly specified no limit - but they could just as easily use 0 to do this, if that's what the API spec defines. So I think requiring non-negative is okay here.
