### ISSUE TITLE
Create issue and PR templates

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#580]

**Comment by vinyxx3** [comment]
hey, I'm naive to contributing... can you kindly tell me what is this issue about and how can I fix it? 😀

**Comment by andrewazores** [comment]
Hi @vinyxx3 . This issue is about what happens when a contributor or bug reporter comes to this repo and either files a new issue (just like you have done here) or opens a new Pull Request. In either case, we want to have some standardized format with some pre-filled form-like content that 1) helps new contributors to create issues with enough detail 2) helps all contributors create Pull Requests linking to the relevant issue 3) helps Pull Request reviewers have enough additional context for the reasons behind a Pull Request, etc.

I think to solve this specific issue you need to already be an established contributor and have modification access to the repository itself, so it isn't an appropriate first issue for you to take on. If you're looking for a low-hanging-fruit issue where you can write some code just let me know and I can try to find something else for you to work on.

**Comment by maxcao13** [comment]
Closed by https://github.com/cryostatio/cryostat/pull/1277

**Comment by maxcao13** [comment]
Closed by https://github.com/cryostatio/cryostat/pull/1277
