### ISSUE TITLE
Posting an invalid XML file as a template results in HTTP 200

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat#601]
If I post an XML file that contains some text that isn't XML, `TemplatesPostHandler` will return HTTP 200. 

The `LocalStorageTemplateService` does not add the invalid file to storage.

See comment [here](https://github.com/cryostatio/cryostat/issues/474#issuecomment-885929234) for more info.

**Comment by jan-law** [comment]
Sorry, it turns out I was making the request incorrectly. The file name in the form should be specified as `template`, not `templateName`. The correct request format works fine:
```
$ curl template=@invalidTemplate.xml https://0.0.0.0:8181/api/v1/templates/
INFO: (10.0.2.100:55462): POST /api/v1/templates/ 400 8ms
```

**Comment by jan-law** [comment]
Wait, I realized it's still a bug if I specify an incorrect form header and the handler returns `200`. I should probably fix that.

**Comment by jan-law** [comment]
When the handler finds a form attribute that does not equal `template`, the code will `continue` by exiting the `for` loop and sending a `200` response without checking the file associated with that form attribute. 

@andrewazores Why does the handler `continue` instead of throwing a `400`? 

```
public void handleAuthenticated(RoutingContext ctx) throws Exception {
        try {
            for (FileUpload u : ctx.fileUploads()) {
                Path path = fs.pathOf(u.uploadedFileName());
                try (InputStream is = fs.newInputStream(path)) {
                    if (!"template".equals(u.name())) {
                        logger.info("Received unexpected file upload named {}", u.name());
                        continue;
                    }
...
```

**Comment by andrewazores** [comment]
That's a pretty good question. Including an unexpected file upload is probably a client error indeed and should get a `400` response. It looks like this was written to try to be lenient and find the expected file name if there is one and just ignore any others, but we should probably be more strict and expect the client to include only the expected upload file.
