### ISSUE TITLE
Fine-tune Kubernetes/OpenShift RBAC permissions

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#635]
https://github.com/cryostatio/cryostat/pull/599#pullrequestreview-723720661

Related #659

**Comment by ebaron** [comment]
We should move away from using FlightRecorder and Recording CRDs here as they are to be deprecated in the operator. See: https://github.com/cryostatio/cryostat-operator/issues/349

**Comment by andrewazores** [comment]
^ https://github.com/cryostatio/cryostat/blob/249df8f2cf0c82aee9698b17979c7e644476ab8a/src/main/java/io/cryostat/net/OpenShiftAuthManager.java#L575
