### ISSUE TITLE
Smoketest error --replace podman flag

### ISSUE THREAD

**Issue by oscerd** [cryostatio/cryostat#684]
Run the smoketest will fail with

`
Error: unknown flag: --replace
`

Podman version is
```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Comment by oscerd** [comment]
Probably it is just related to podman version.

**Comment by andrewazores** [comment]
Most likely, yes.

```
$ podman --version
podman version 3.3.0
```

In the README we do stipulate podman 2.0+.

Please re-open this if you can still reproduce the issue with a later 2.0+ version of podman.

**Comment by oscerd** [comment]
Yeah, following the instructions for centos, through yum I'm getting 1.6.4., I'll update and post back.
