### ISSUE TITLE
WebSocket keepalive/pings

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#757]
@jan-law Try adding these annotations to each Ingress:
```
nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
```
This seems to be the recommended solution from the NGINX Ingress documentation: https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#websockets

_Originally posted by @ebaron in https://github.com/cryostatio/cryostat-operator/issues/279#issuecomment-983039470_

**Comment by jan-law** [comment]
This `cryostat.yaml` configuration keeps the connection alive. I don't see any more WebSocket notifications.
```
jalaw@localhost ~/install-operator> kubectl get cryostat -o yaml
apiVersion: v1
items:
- apiVersion: operator.cryostat.io/v1beta1
  kind: Cryostat
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.cryostat.io/v1beta1","kind":"Cryostat","metadata":{"annotations":{},"name":"cryostat-sample","namespace":"default"},"spec":{"minimal":false,"networkOptions":{"commandConfig":{"annotations":{"nginx.ingress.kubernetes.io/backend-protocol":"HTTPS","nginx.ingress.kubernetes.io/proxy-read-timeout":"3600","nginx.ingress.kubernetes.io/proxy-send-timeout":"3600"},"ingressSpec":{"rules":[{"host":"testing.cryostat-command","http":{"paths":[{"backend":{"service":{"name":"cryostat-sample-command","port":{"number":9090}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{}]}},"coreConfig":{"annotations":{"nginx.ingress.kubernetes.io/backend-protocol":"HTTPS","nginx.ingress.kubernetes.io/proxy-read-timeout":"3600","nginx.ingress.kubernetes.io/proxy-send-timeout":"3600"},"ingressSpec":{"rules":[{"host":"testing.cryostat","http":{"paths":[{"backend":{"service":{"name":"cryostat-sample","port":{"number":8181}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{}]}},"grafanaConfig":{"annotations":{"nginx.ingress.kubernetes.io/backend-protocol":"HTTPS","nginx.ingress.kubernetes.io/proxy-read-timeout":"3600","nginx.ingress.kubernetes.io/proxy-send-timeout":"3600"},"ingressSpec":{"rules":[{"host":"testing.cryostat-grafana","http":{"paths":[{"backend":{"service":{"name":"cryostat-sample-grafana","port":{"number":3000}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{}]}}}}}
    creationTimestamp: "2021-11-30T22:01:47Z"
    finalizers:
    - operator.cryostat.io/cryostat.finalizer
    generation: 1
    name: cryostat-sample
    namespace: default
    resourceVersion: "46721"
    uid: e5f708c9-29c4-4514-a958-fde9e8bbfcd3
  spec:
    minimal: false
    networkOptions:
      commandConfig:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        ingressSpec:
          rules:
          - host: testing.cryostat-command
            http:
              paths:
              - backend:
                  service:
                    name: cryostat-sample-command
                    port:
                      number: 9090
                path: /
                pathType: Prefix
          tls:
          - {}
      coreConfig:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        ingressSpec:
          rules:
          - host: testing.cryostat
            http:
              paths:
              - backend:
                  service:
                    name: cryostat-sample
                    port:
                      number: 8181
                path: /
                pathType: Prefix
          tls:
          - {}
      grafanaConfig:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        ingressSpec:
          rules:
          - host: testing.cryostat-grafana
            http:
              paths:
              - backend:
                  service:
                    name: cryostat-sample-grafana
                    port:
                      number: 3000
                path: /
                pathType: Prefix
          tls:
          - {}
  status:
    applicationUrl: https://testing.cryostat
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by jan-law** [comment]
Since these annotations apply only to Kubernetes, what would be the OpenShift equivalent of setting the nginx timeouts?

**Comment by andrewazores** [comment]
I think you still will with that configuration, but the disconnect period will be 1 hour and so it will be much less noticeable or disturbing. If we have some kind of keepalive/ping that is transmitted over the connection at some short interval of say ~5s, then a proxying server configuration should count that as activity and not time out the connection.

**Comment by jan-law** [comment]
Do you mean we should include the 3600 timeout in addition to adding a keepalive/ping at 5s? As long as the ping occurs at a shorter interval than the timeout then the connection should stay alive.

**Comment by ebaron** [comment]
> Since these annotations apply only to Kubernetes, what would be the OpenShift equivalent of setting the nginx timeouts?

I found this in the OpenShift documentation: https://docs.openshift.com/container-platform/4.9/networking/routes/route-configuration.html

Variable | Default | Description
-- | -- | --
ROUTER_DEFAULT_TUNNEL_TIMEOUT | 1h | Length of time for TCP or WebSocket connections to remain open. This timeout period resets whenever HAProxy reloads.

So it would be an hour by default, but I don't see an annotation to modify it when creating the Route.

**Comment by andrewazores** [comment]
If the 3600 timeout is useful for packaging/productization/downstream type things like OperatorHub then I think it's probably a good idea to include that configuration for now. Once we have an upstream release that includes application-level keepalive then the downstream configuration for increasing the timeout can be removed.

**Comment by andrewazores** [comment]
> > Since these annotations apply only to Kubernetes, what would be the OpenShift equivalent of setting the nginx timeouts?
> 
> I found this in the OpenShift documentation: https://docs.openshift.com/container-platform/4.9/networking/routes/route-configuration.html
> Variable 	Default 	Description
> ROUTER_DEFAULT_TUNNEL_TIMEOUT 	1h 	Length of time for TCP or WebSocket connections to remain open. This timeout period resets whenever HAProxy reloads.
> 
> So it would be an hour by default, but I don't see an annotation to modify it when creating the Route.

That would definitely explain why this behaviour shows up so easily in minikube and not in CRC!

**Comment by ebaron** [comment]
> > Since these annotations apply only to Kubernetes, what would be the OpenShift equivalent of setting the nginx timeouts?
> 
> I found this in the OpenShift documentation: https://docs.openshift.com/container-platform/4.9/networking/routes/route-configuration.html
> Variable 	Default 	Description
> ROUTER_DEFAULT_TUNNEL_TIMEOUT 	1h 	Length of time for TCP or WebSocket connections to remain open. This timeout period resets whenever HAProxy reloads.
> 
> So it would be an hour by default, but I don't see an annotation to modify it when creating the Route.

For future reference: there does appear to be annotation for OpenShift routes: `haproxy.router.openshift.io/timeout-tunnel` [1]

[1] https://docs.openshift.com/container-platform/4.9/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration
