### ISSUE TITLE
[Story] Enable/disable Automated Rules

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#773]
Currently, for a client to activate an Automated Rule, they must do `POST /api/v2/rules` to create the rule definition, which becomes effective immediately. To disable this rule they must do `DELETE /api/v2/rules/:ruleName`, which removes the rule definition and prevents it from activating in the future. The `?clean=true` query parameter can be included on the `DELETE` request to stop and remove all `ACTIVE` recordings that were created by the Automated Rule.

Would it also make sense to add an `enabled: boolean` state to Automated Rule definitions? This could be accompanied by a `PATCH /api/v2/rules/:ruleName` handler for modifying the `enabled` status. When a rule is first `POST`ed it may include `enabled: true` in the definition so that it is activated immediately. If `enabled: false` or if `enabled` is not included in the definition then the Automated Rule is still created but is left inactive, and the `RuleProcessor` will not apply the rule to any current or future targets until the rule is enabled.

This somewhat mimics the API for Active Recordings, where a Recording is in a `RUNNING` state when created and a `PATCH` request can be made to either snapshot or stop the recording. Stopping an Active Recording is somewhat analogous to disabling an Automated Rule.

The first advantage here is that end users would be able to define an Automated Rule and have it persisted in Cryostat's storage, but not necessarily to have it actually triggering at all times. This is perhaps simpler on the user's end than the `POST/DELETE` flow currently required, and would help to ensure that users don't accidentally `DELETE` a rule to disable it and then accidentally re-`POST` a different rule definition when trying to re-enable it.

The second advantage, which is perhaps more compelling, is that this would make it very easy and straightforward for Cryostat to ship with some basic and generic Automated Rule definitions out of the box as JSON file assets embedded in the container image, just like the `cryostat.jfc` Event Template. Some examples:

`monitoring.json`
```json
{
  "name":"monitoring",
  "description":"Enable the 'default' Continuous monitoring event template on all targets",
  "matchExpression": true,
  "eventSpecifier":"template=Continuous,type=TARGET",
  "enabled": false
}
```

`openshift-monitoring.json`
```json
{
  "name":"openshift-monitoring",
  "description":"Enable the 'default' Continuous monitoring event template on all targets with OpenShift annotation 'cryostat.io/monitoring: true`. Copy JFR data to archives every 5 minutes and maintain 1 hour of archives.",
  "matchExpression": "target.annotations.platform['cryostat.io/monitoring']==true",
  "eventSpecifier":"template=Continuous,type=TARGET",
  "enabled": false,
  "archivalPeriodSeconds": 300,
  "preservedArchives": 12
}
```

A carry-over benefit of shipping such rule profiles as part of the container image is that they would act as easy templates for users to start from when customizing their own tailored rule definitions - again, just like downloading an existing `type=TARGET` Event Template and editing it to customize and tailor to their application.

**Comment by lkonno** [comment]
When I worked with the rules, I felt that it could be great to be able to enable/disable the rules. 
I am working on a new handler for the patch method. Should it be created in the io.cryostat.net.web.http.api.beta package?

**Comment by andrewazores** [comment]
I think that handler can go right into the v2 package as an `ApiVersion.V2_2`. It's a small addition to an existing API and unlikely to change in the future. The `beta` package/API version is more meant for things that are fairly likely to change, like the path might change or the handler could be dropped entirely for the next release etc.

**Comment by lkonno** [comment]
OK, I was unsure about the beta packages usage. Thanks!
