### ISSUE TITLE
The "Token Authentication" section in https://cryostat.io/get-started/ should also be updated when this OAuth feature becomes available in the next Cryostat release.

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#791]
Note: The "Token Authentication" section in https://cryostat.io/get-started/ should also be updated when this OAuth feature becomes available in the next Cryostat release.

_Originally posted by @jan-law in https://github.com/cryostatio/cryostat/issues/786#issuecomment-1010414106_

**Comment by jan-law** [comment]
I'm thinking it would make sense to put the new Token Authentication section in a "2.1.0 Getting Started" post and leaving the "2.0.0 Getting Started" page as is. We could include the version drop down already used by the Guides page. 

Will put this issue on hold for now until the next release.
