### ISSUE TITLE
Template download fails with message "Needs Authorization"

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat#802]
When running cryostat locally, attempting to download a template from the /events tab results in a `401`, even though the `POST` request for the JWT token returns `200`.

```
Jan 21, 2022 10:34:31 PM io.cryostat.core.log.Logger info
INFO: (10.0.2.100:59668): GET /api/v1/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Fcryostat%3A9091%2Fjmxrmi/templates 200 147ms
Jan 21, 2022 10:34:31 PM io.cryostat.core.log.Logger info
INFO: (10.0.2.100:59666): GET /api/v1/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Fcryostat%3A9091%2Fjmxrmi/events 200 261ms
Jan 21, 2022 10:34:34 PM io.cryostat.core.log.Logger info
INFO: (10.0.2.100:59666): POST /api/beta/auth/token 200 101ms
Jan 21, 2022 10:34:34 PM io.cryostat.core.log.Logger warn
WARNING: HTTP 401: Unauthorized
io.cryostat.net.web.http.api.v2.ApiException: Unauthorized
Jan 21, 2022 10:34:34 PM io.cryostat.core.log.Logger info
INFO: (10.0.2.100:59666): GET /api/beta/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Fcryostat%3A9091%2Fjmxrmi/templates/Cryostat/type/TARGET 401 11ms
```

**Comment by andrewazores** [comment]
Interesting. I can reproduce this with a simple `sh smoketest.sh` and trying to download the template with Firefox or Chromium browsers. When I try what I think is the same JWT token download flow using HTTPie it works as expected. But, if I make the request using a browser with the devtools network inspector open I can see the token request, for example:

![image](https://user-images.githubusercontent.com/3787464/151419786-a3dd601b-0e81-4689-b92a-2f38c282cd62.png)

The API response is:

```json
{"meta":{"type":"application/json","status":"OK"},"data":{"result":{"resourceUrl":"/api/beta/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Fcryostat%3A9093%2Fjmxrmi/templates/Profiling/type/TARGET?token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..W2gYmNJuLgiKYNb0.5Y_WL3vDeZODpH45jqF9jObwkxyRFBu8QOT1Npu8a673Gk67NS2gDYd4-35cQVtjFbvqf-dtmX3bgdTnqLCT2koVbib-SFUYvW0ccks9sxcXVAXCgxAtQFzVYoYIcu7cb-UP507wA9DYBVy2qkI54zX_qdvOuvHygsDd12y21MdZJ0sbU50nx76AYhytRTaPnDPEwJChuNd95oou7pCMgYhuenYInHGLMXX1yWFTZRWabaHgDmLk_hO_8q1XlGUczpKp_w-CSyufcbTCbzHMoAsjo4AI9A46KNYBXVhfiX27I5qRHdV7fS9IAFaH19bzxCE9msH3dbZYO3yxMv8L8Kpn1R6ufrv3x8p30Fav-IibEche3eWQw7nNDiPX7q3vAdo4ZNzhY2KhzJ3G98gwUbmftn9yna3EBBPaQEv_PhVyjxD0eHD1G2OpBHHuemvkcZYbOJXBxne7kTQdq8JMVJ_aoVp-zXWAPVgUPPUrSP8CAtJX-IWqKnzCd4h5beEl85NwglRJAQJH3KNwkDQ5XcPt0dIOqvhRcXtJiFs_IVuIPMXUFKcRi4kceKtlO-OILq5c.kuyCyDmROn6Q0XT9hIwGqw"}}}
```

If I try to use this token with HTTPie however:

```
https :8181/api/beta/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Fcryostat%3A9093%2Fjmxrmi/templates/Profiling/type/TARGET?token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..W2gYmNJuLgiKYNb0.5Y_WL3vDeZODpH45jqF9jObwkxyRFBu8QOT1Npu8a673Gk67NS2gDYd4-35cQVtjFbvqf-dtmX3bgdTnqLCT2koVbib-SFUYvW0ccks9sxcXVAXCgxAtQFzVYoYIcu7cb-UP507wA9DYBVy2qkI54zX_qdvOuvHygsDd12y21MdZJ0sbU50nx76AYhytRTaPnDPEwJChuNd95oou7pCMgYhuenYInHGLMXX1yWFTZRWabaHgDmLk_hO_8q1XlGUczpKp_w-CSyufcbTCbzHMoAsjo4AI9A46KNYBXVhfiX27I5qRHdV7fS9IAFaH19bzxCE9msH3dbZYO3yxMv8L8Kpn1R6ufrv3x8p30Fav-IibEche3eWQw7nNDiPX7q3vAdo4ZNzhY2KhzJ3G98gwUbmftn9yna3EBBPaQEv_PhVyjxD0eHD1G2OpBHHuemvkcZYbOJXBxne7kTQdq8JMVJ_aoVp-zXWAPVgUPPUrSP8CAtJX-IWqKnzCd4h5beEl85NwglRJAQJH3KNwkDQ5XcPt0dIOqvhRcXtJiFs_IVuIPMXUFKcRi4kceKtlO-OILq5c.kuyCyDmROn6Q0XT9hIwGqw
HTTP/1.1 401 Unauthorized
X-WWW-Authenticate: None
content-encoding: gzip
content-length: 127
content-type: application/json

{
    "data": {
        "reason": "Token resource claim does not match requested resource"
    },
    "meta": {
        "status": "Unauthorized",
        "type": "text/plain"
    }
}
```

(I had to add the `:8181` to the URL for HTTPie, otherwise I just copy-pasted the URL from the token response)

then we see the `401/Unauthorized` message which is presumably what causes the "Needs Authorization" message to appear.

The "Token resource claim does not match requested resource" seems telling.

**Comment by andrewazores** [comment]
Here's an example of just using HTTPie the whole way through to perform the expected template download flow:

```
$ https -f :8181/api/beta/auth/token resource=/api/v1/targets/localhost:0/templates/Continuous/type/TARGET
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 587
content-type: application/json

{
    "data": {
        "result": {
            "resourceUrl": "/api/v1/targets/localhost:0/templates/Continuous/type/TARGET?token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..7X28d5eMR5tpqKUT.KLl3CbXY6Xu_OyNewjw7PLxCsAhHkWPZTmxB3x9Z_zufmXAmWJlkTqVuXynZFrTG_C_BhUp-bcYBBoQkEVIQ5ZWwiNHMafAU2JUiYDPLxnoEBiLszy4iF2g4D0NuegZonMvHDZb4mqofr-VD06STdiWnri3rqpOGeUuTT2SVPgIjnBCZDhIuZl9ZCVJ4yAisDm3OXF0q8ZuOdNhmepyCCkzjCzhd6vgYWmTa9ejIwEj9_202j-GqdwGT6hSwH2flohBxGF-TZfIaeLxRas-F0-4CtRPh55MQ-HbVlE1WFcXEIRHaehybAEa5FqVU3YViDk5kTDVOHlsSC5B7RS_B3htNByFi-FcLJjcFiiFzQKmhfQdQGBiPoRUylDgWcFwVSgfjZUkR911bwHdzSmWhwAJ-u-EDWKhAZF26asCRKH5oEvoQPjxu7aFdcFs.jlEeNdRnurnxcNKZ76kDvg"
        }
    },
    "meta": {
        "status": "OK",
        "type": "application/json"
    }
}


$ https :8181/api/v1/targets/localhost:0/templates/Continuous/type/TARGET?token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..7X28d5eMR5tpqKUT.KLl3CbXY6Xu_OyNewjw7PLxCsAhHkWPZTmxB3x9Z_zufmXAmWJlkTqVuXynZFrTG_C_BhUp-bcYBBoQkEVIQ5ZWwiNHMafAU2JUiYDPLxnoEBiLszy4iF2g4D0NuegZonMvHDZb4mqofr-VD06STdiWnri3rqpOGeUuTT2SVPgIjnBCZDhIuZl9ZCVJ4yAisDm3OXF0q8ZuOdNhmepyCCkzjCzhd6vgYWmTa9ejIwEj9_202j-GqdwGT6hSwH2flohBxGF-TZfIaeLxRas-F0-4CtRPh55MQ-HbVlE1WFcXEIRHaehybAEa5FqVU3YViDk5kTDVOHlsSC5B7RS_B3htNByFi-FcLJjcFiiFzQKmhfQdQGBiPoRUylDgWcFwVSgfjZUkR911bwHdzSmWhwAJ-u-EDWKhAZF26asCRKH5oEvoQPjxu7aFdcFs.jlEeNdRnurnxcNKZ76kDvg
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 3037
content-type: application/jfc+xml

<?xml version="1.0" encoding="UTF-8"?>
...
```

**Comment by jan-law** [comment]
> If I try to use this token with HTTPie however:

I noticed the `resourceUrl` returned from the web-client token starts with `/api/beta`

> Here's an example of just using HTTPie the whole way through to perform the expected template download flow:

This `resourceUrl` starts with `/api/v1`...

**Comment by andrewazores** [comment]
Aha, good catch. I've made a mistake in my HTTPie example then - the second request is going to the v1 handler, which just ignores the JWT token and instead uses the normal Authorization header check, which simply passes since this is smoketesting and no auth is enabled.

**Comment by andrewazores** [comment]
```
$ https -f :8181/api/beta/auth/token resource=/api/beta/targets/localhost:0/templates/Continuous/type/TARGET
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 591
content-type: application/json

{
    "data": {
        "result": {
            "resourceUrl": "/api/beta/targets/localhost:0/templates/Continuous/type/TARGET?token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..2vSBLCRj51LTBx5-.HCgr_WrWDO_gQD9aabArt-SV_kOGB_qTnVe-gpuDSn2j75e_tgvCjDU1KiuEq5gjrHQ7u-ty3TODp9A-GIFERKlZLHohfTUOJJNpB-oa0HDSXBnrO11Z6wicNqUuXbN3q4PPlZdkFX4K698oFg1Abi47-D4rWxw98W1r08y6g93tY7Wk2YSj2uqAwiW7ktzHlcyQwIWBdxFUHQEvoqROgwoSiUFwP2At_6CSJl5d0rEh6pEHNt111YHGF6yrdeprIp5AnrSYd9vCnrBQmI_FC49Lrz5KWCdzQeAfE_Ke4GYwK64sT9ZH8oC7pWId0Bz4yN0iMXvfDrmx6xuW1itkRiqx0LdWb3ahA1wV8l7fCHiOBbrkLJ99Wibrmdo0U8ljcdX21iySjAuP_rYMmlrkbxcm3LhjKSaAC4Lwm_E40wKcPL0NQz9_a9JB8oJUBiI.NZOeHr0yn5FsXbwxrWUjfg"
        }
    },
    "meta": {
        "status": "OK",
        "type": "application/json"
    }
}


$ https :8181/api/beta/targets/localhost:0/templates/Continuous/type/TARGET?token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..2vSBLCRj51LTBx5-.HCgr_WrWDO_gQD9aabArt-SV_kOGB_qTnVe-gpuDSn2j75e_tgvCjDU1KiuEq5gjrHQ7u-ty3TODp9A-GIFERKlZLHohfTUOJJNpB-oa0HDSXBnrO11Z6wicNqUuXbN3q4PPlZdkFX4K698oFg1Abi47-D4rWxw98W1r08y6g93tY7Wk2YSj2uqAwiW7ktzHlcyQwIWBdxFUHQEvoqROgwoSiUFwP2At_6CSJl5d0rEh6pEHNt111YHGF6yrdeprIp5AnrSYd9vCnrBQmI_FC49Lrz5KWCdzQeAfE_Ke4GYwK64sT9ZH8oC7pWId0Bz4yN0iMXvfDrmx6xuW1itkRiqx0LdWb3ahA1wV8l7fCHiOBbrkLJ99Wibrmdo0U8ljcdX21iySjAuP_rYMmlrkbxcm3LhjKSaAC4Lwm_E40wKcPL0NQz9_a9JB8oJUBiI.NZOeHr0yn5FsXbwxrWUjfg
HTTP/1.1 401 Unauthorized
X-WWW-Authenticate: None
content-encoding: gzip
content-length: 127
content-type: application/json

{
    "data": {
        "reason": "Token resource claim does not match requested resource"
    },
    "meta": {
        "status": "Unauthorized",
        "type": "text/plain"
    }
}
```

There's the corrected HTTPie example workflow. It matches what the browsers are seeing now.

**Comment by andrewazores** [comment]
Using an absolute URL for the JWT resource works:

```
$ https -f :8181/api/beta/auth/token resource=https://localhost:8181/api/beta/targets/localhost:0/templates/Continuous/type/TARGET
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 637
content-type: application/json

{
    "data": {
        "result": {
            "resourceUrl": "https://localhost:8181/api/beta/targets/localhost:0/templates/Continuous/type/TARGET?token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..LMHEyEl6UGbBxiTa.Jq-wtZneNU1yJpnBrDPwdTDfVo7U0zuH6_Xt5cQROnow1xpcg3gyHjderwlPnHUR53GvVBobIAGE9mFs33nUDCOHcfSSdKcBv_7sNfTezgkP5VBZKYvglOwvQA1Nd3Maf4LISGro7B10dkYxEPjRJkfeNvqmHpUqKIWdX96lMogslzwNtetLNC3EogcXW0dYDMF80ju0wrSoaKDPPf8B4jqUVZrQbqj-DycgU7LggP_2pjM6KI70i1JS-BOxa_4PVwjn-0lghsfBCxQlU7a7SjDacVyll6qJLKjWeaaxpl1c2VjOZL2DyvSMN4Q1akZurx7KxIEVNOam3ngcw-gqr0x08H6anYsElbeKEo8NqG7IqJ3Xu_Q493jCz4cVkYDYgxx4aoohjX6rcCyhTdbnFdiQvRUMyY5H0goFoW7xab50qcC9xA2GtJzdKG_5vfyy7f04Loj5c1U1bd2I-zNrMwUx5getAyuZuFU0JMO8Hg.1eHt0zLh0bo2vwl1eqG-EQ"
        }
    },
    "meta": {
        "status": "OK",
        "type": "application/json"
    }
}


$ https https://localhost:8181/api/beta/targets/localhost:0/templates/Continuous/type/TARGET?token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..LMHEyEl6UGbBxiTa.Jq-wtZneNU1yJpnBrDPwdTDfVo7U0zuH6_Xt5cQROnow1xpcg3gyHjderwlPnHUR53GvVBobIAGE9mFs33nUDCOHcfSSdKcBv_7sNfTezgkP5VBZKYvglOwvQA1Nd3Maf4LISGro7B10dkYxEPjRJkfeNvqmHpUqKIWdX96lMogslzwNtetLNC3EogcXW0dYDMF80ju0wrSoaKDPPf8B4jqUVZrQbqj-DycgU7LggP_2pjM6KI70i1JS-BOxa_4PVwjn-0lghsfBCxQlU7a7SjDacVyll6qJLKjWeaaxpl1c2VjOZL2DyvSMN4Q1akZurx7KxIEVNOam3ngcw-gqr0x08H6anYsElbeKEo8NqG7IqJ3Xu_Q493jCz4cVkYDYgxx4aoohjX6rcCyhTdbnFdiQvRUMyY5H0goFoW7xab50qcC9xA2GtJzdKG_5vfyy7f04Loj5c1U1bd2I-zNrMwUx5getAyuZuFU0JMO8Hg.1eHt0zLh0bo2vwl1eqG-EQ
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 3037
content-type: application/jfc+xml

<?xml version="1.0" encoding="UTF-8"?>
...
```

**Comment by jan-law** [comment]
It looks like the backend expects the `resourceUrl` to contain the protocol and authority. `Objects.equals(fullRequestUri, resourceClaim)` evaluates to false.

Since the request succeeds as long as the requested and expected urls are the same, I think I can fix this by changing the frontend to request a resourceURI with an absolute URL.

```
{"meta":{"type":"text/plain","status":"Unauthorized"},"data":{"reason":"Token resource claim does not match requested resource. 
Expected: http://localhost:8181/api/beta/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Fcryostat%3A9091%2Fjmxrmi/templates/Profiling/type/TARGET 
Actual: /api/beta/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Fcryostat%3A9091%2Fjmxrmi/templates/Profiling/type/TARGET"}}
```

**Comment by andrewazores** [comment]
Yea, that makes sense to me. It looks like we basically just need to prepend the authority string to the resource string that it constructs for itself already.

**Comment by jan-law** [comment]
I noticed the code already includes `${this.login.authority}` ([link to code](https://github.com/cryostatio/cryostat-web/blob/main/src/app/Shared/Services/Api.service.tsx#L378)) when constructing the resource string. Except when I build the web-client with `mvn clean package`, I noticed all the `/beta/token` requests send the request url as a relative url without an authority string.

I think the web-client gets built with the production configurations when I run `mvn clean package`, which I think would use `.env.prod` instead of `.env`. `CRYOSTAT_AUTHORITY` is blank in `.env.prod`. This might explain why I can only download templates if I build the web client with `yarn start:dev`. Since it doesn't seem right to modify the prod configurations, could we maybe add another build command in `package.json` that builds the web client with the dev configuration, and use that for running cryostat locally?

```
$ mvn clean package
...
[INFO] --- frontend-maven-plugin:1.11.3:yarn (yarn run build) @ cryostat ---
[INFO] Running 'yarn run build' in /home/jalaw/cryostat/web-client
[INFO] yarn run v1.22.13
[INFO] $ webpack --config webpack.prod.js
```

**Comment by andrewazores** [comment]
Right, `.env` is used for dev mode and `.env.prod` for full builds, which are what get packaged into the whole Cryostat OCI image when you do a `mvn package`.

> This might explain why I can only download templates if I build the web client with yarn start:dev

Makes sense...

> could we maybe add another build command in package.json that builds the web client with the dev configuration, and use that for running cryostat locally?

Maybe - I'm not sure what you mean by "for running cryostat locally" here, though. The `.env.prod` uses an empty authority string because that basically causes the URLs generated by the `Api.service` etc. to become relative URLs, so the client browser is what determines where the instance is running and where to actually send that relative URL request to. If we set the authority string to some non-empty value and package that into an OCI image then that OCI image becomes deployment-specific - it needs to have been built with an authority string that matches the scheme/host/port of where the OCI image will actually be running.

Maybe the fix we need is to instead modify the backend where it handles processing the JWT token and checking the origin, and have it be ever so slightly more lenient. If it's given an absolute URL then the authority portion must match. If it's given a relative URL then the authority portion implicitly matches, but the rest of the URL (the path, really) still needs to match?

Otherwise, maybe we can work around this by adding an API handler that just reports the scheme/host/port being used by the backend. This is redundant information for any client that already knows how to contact the backend server, but it could be used by the web-client on startup to initialize its authority value with the actual location of the backend it's being served from. Or instead of adding a new API handler just for this, maybe this could simply be an extra key:value pair in the object returned by the `/health` handler.

**Comment by jan-law** [comment]
> The .env.prod uses an empty authority string because that basically causes the URLs generated by the Api.service etc. to become relative URLs, so the client browser is what determines where the instance is running and where to actually send that relative URL request to

Okay, that makes more sense now.

> Maybe the fix we need is to instead modify the backend where it handles processing the JWT token and checking the origin, and have it be ever so slightly more lenient. If it's given an absolute URL then the authority portion must match. If it's given a relative URL then the authority portion implicitly matches, but the rest of the URL (the path, really) still needs to match?

This fix looks more flexible and would also let you HTTPie token resources with relative URLs.
