### ISSUE TITLE
GraphQL filtering strategy

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#825]
Using input objects as a sort of filter configuration seems to make sense. This allows the query's type signature to be short and sweet, and also makes it easy to extend the configuration input type with more filter kinds in the future. However, we need to decide what happens if a user specifies multiple of the optional fields within the configuration object. If a user is querying active recordings and applies a filter with both a "continuous==true" and "labels['myLabel']=='something'`, does this filter match recordings with both properties or with either property? It seems unclear. I suggest that it should be an "AND", since this allows the user to perform very narrow requests on pairs of properties that are computed server-side, alleviating a lot of requests and filtering work on the client side. If the user needs to do an equivalent "OR" then they can do so by decomposing their request into multiple requests where each filter property is supplied once on its own.

Another option is as @ebaron suggests, to re-use [Kubernetes label selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors) via the fabric8 client. If we do this then it should not only be limited to labels, and we should come up with a way to also apply this to other metadata about resources, so that the selector syntax can be the entire filter syntax rather than just a portion of the filter specifically for the labels field. The first, perhaps naive, solution that comes to mind is to copy these other fields into the labels map with some well-known key prefix, and perhaps to also prepend any actual labels with another prefix for consistency.

Consider following node resource (JSON-ish):

```
TargetNode {
  name: "myNode",
  kind: "JVM",
  annotations: {
    "myAnnotation": "anno1"
  },
  labels: {
    "com.example.MyApp/label": "labelled"
  }
}
```

This could be converted into a simple Map (made up syntax) to be processed using the label selector syntax:

```
  cryostat.node.name -> myNode
  cryostat.node.kind -> JVM
  cryostat.annotations.myAnnotation -> anno1
  cryostat.labels.com.example.MyApp/label -> labelled
```

**Comment by andrewazores** [comment]
> The query will treat the input object with the same overall logic as Kubernetes does for label selectors: a null input matches nothing, and an "empty" input (object containing no key-value pairs) matches everything.

Actually, I want to revise this. As stated the user always needs to provide a filter input object or else they receive no query results. And since every condition within the filter is `AND`ed together, the filter input object would always need to contain an empty string for a label selector filter once those are implemented.

So I think in this case we want to roughly flip it - a `null` or empty filter input object matches everything. The filter input object containing no label selector (null/undefined) means that the filter doesn't apply and so effectively all labels are accepted. If the filter object contains a label selector and that selector is an empty string then it will still accept everything.

**Comment by hareetd** [comment]
I like this strategy; it's logically consistent, especially with regards to how `null` and empty objects are handled. The ability to do set-based and equality-based matching like the Kubernetes label selectors provide adds some flexibility to the queries as well.

**Comment by jan-law** [comment]
> since every condition within the filter is ANDed together, the filter input object would always need to contain an empty string for a label selector filter once those are implemented

> If the user needs to do an equivalent "OR" then they can do so by decomposing their request into multiple requests where each filter property is supplied once on its own.

Agreed, it makes sense to `AND` all the filter parameters together.

**Comment by andrewazores** [comment]
Closing this since the strategy has been settled upon and now it's down to finishing the implementation.

**Comment by andrewazores** [comment]
@ebaron I just realized we have a grammar incompatibility between k8s label selectors and our current form of template specifier. We use ex. `template=Profiling,type=TARGET` to specify the event template to use to start a recording, and we capture that string verbatim and store it in the metadata labels attached to a recording (active or archived), with the map key `template`. For example:

```json
{
    "data": {
        "environmentNodes": [
            {
                "descendantTargets": [
                    {
                        "recordings": {
                            "active": [
                                {
                                    "metadata": {
                                        "labels": {
                                            "template": "template=Profiling,type=TARGET"
                                        }
                                    },
                                    "name": "foo",
                                    "state": "RUNNING"
                                }
                            ],
                            "archived": []
                        }
                    }
                ],
                "labels": {},
                "name": "JDP",
                "nodeType": "Realm"
            }
        ]
    }
}
```

This is incompatible with both the equality-based and set-based k8s label selector syntaxes. The equality style expression would look like `template = template=Profiling,type=TARGET` and the set style expression would look like `template in (template=Profiling,type=TARGET)`. Both of these are ambiguous and invalid because our `template=Foo[,type=TYPE]` expression is not a valid k8s label value.

Possible solutions:

1. Maintain the existing `templateLabel` special case label selector style, where the filter input simply takes the expected value of the label, and not a full label selector expression. All other kinds of label can be selected normally with k8s selector style.
2. Change our `template=Foo[,type=TYPE]` syntax. Doesn't seem appropriate for 2.1.0.
2b. We could alternately maintain the same input syntax, but replace the delimiters to something k8s label selector compatible when persisting them into recording metadata.
3. Implement some more specialized parser for the label selectors that can handle this ambiguous case for our specific scenario, but this is pretty hacky and can still end up being ambiguous with our template specifier syntax anyway.

Thoughts? For 2.1.0, option 1 seems to make the most sense to me, or maybe 2b. For 3.0 we can change the event specifier syntax and avoid this issue entirely.

**Comment by ebaron** [comment]
> @ebaron I just realized we have a grammar incompatibility between k8s label selectors and our current form of template specifier. We use ex. `template=Profiling,type=TARGET` to specify the event template to use to start a recording, and we capture that string verbatim and store it in the metadata labels attached to a recording (active or archived), with the map key `template`. For example:
> 
> ```json
> {
>     "data": {
>         "environmentNodes": [
>             {
>                 "descendantTargets": [
>                     {
>                         "recordings": {
>                             "active": [
>                                 {
>                                     "metadata": {
>                                         "labels": {
>                                             "template": "template=Profiling,type=TARGET"
>                                         }
>                                     },
>                                     "name": "foo",
>                                     "state": "RUNNING"
>                                 }
>                             ],
>                             "archived": []
>                         }
>                     }
>                 ],
>                 "labels": {},
>                 "name": "JDP",
>                 "nodeType": "Realm"
>             }
>         ]
>     }
> }
> ```
> 
> This is incompatible with both the equality-based and set-based k8s label selector syntaxes. The equality style expression would look like `template = template=Profiling,type=TARGET` and the set style expression would look like `template in (template=Profiling,type=TARGET)`. Both of these are ambiguous and invalid because our `template=Foo[,type=TYPE]` expression is not a valid k8s label value.
> 
> Possible solutions:
> 
>     1. Maintain the existing `templateLabel` special case label selector style, where the filter input simply takes the expected value of the label, and not a full label selector expression. All other kinds of label can be selected normally with k8s selector style.
> 
>     2. Change our `template=Foo[,type=TYPE]` syntax. Doesn't seem appropriate for 2.1.0.
>        2b. We could alternately maintain the same input syntax, but replace the delimiters to something k8s label selector compatible when persisting them into recording metadata.
> 
>     3. Implement some more specialized parser for the label selectors that can handle this ambiguous case for our specific scenario, but this is pretty hacky and can still end up being ambiguous with our template specifier syntax anyway.
> 
> 
> Thoughts? For 2.1.0, option 1 seems to make the most sense to me, or maybe 2b. For 3.0 we can change the event specifier syntax and avoid this issue entirely.

Would splitting this label into `template.name` and `template.type` be a major change?

**Comment by andrewazores** [comment]
On the input side yes, I think that would be pretty major and I don't really want to make that change for 2.1.0. If we just change to that for how we store it as labels, then I think that falls under the '2b' solution, although probably even better since it makes it easier for clients to query about those two linked properties separately.

I'll file a bug for that and handle it separately from the label selector implementation.
