### ISSUE TITLE
TargetsPostHandler (Custom Target creation) is undocumented

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#840]
`HTTP_API.md` is missing an entry for the V2 API that allows for custom target creation.

**Comment by jan-law** [comment]
I was looking at our [custom target blog post](https://developers.redhat.com/articles/2021/11/02/java-monitoring-custom-targets-cryostat#) to understand when someone would want to use the `TargetsPostHandler`. 
When the post says "developers can now create connections by providing custom URLs for known potential Java application targets that are valid but not yet discoverable.", what does "not yet discoverable" mean? Would disabling JDP affect this automatic target discovery?

**Comment by andrewazores** [comment]
Automatic target discovery generally just means whichever one is selected by the PlatformModule, or whatever PlatformClient the deploying user explicitly selects by environment variable. So in the case of the `DefaultPlatformClient`, that's actually listening for JDP multicast to discover targets. Targets that are reachable on the network but which do not have JDP enabled will never be found by the `DefaultPlatformClient`, but if the user knows that such a target exists then they can define a custom target to point to it and let Cryostat know that it's actually there.

Likewise, when deployed in OpenShift, the `KubeApiPlatformClient` is used, and this discovers targets by querying for and listening for Endpoints objects. One Endpoints corresponds to one <Pod, Port> pair - so a Service pointing at a Deployment with 2 replicas will result in 2 Endpoints, one for each Pod/Port pair. But we filter these by `port.number == 9091 || port.name == 'jfr-jmx'`. So, if the user knows that they have an application deployed in their OpenShift namespace and this application has a Pod with at least 1 replica and a Service pointing at it, but the port name and number are incorrect, then the user can use a custom target definition to hook it up to Cryostat. This might be useful if the user just needs to connect to the application once for a one-off troubleshooting or profiling session, not as an ongoing/long-term monitoring infrastructure deployment, and so they don't want to edit the Service object to add an additional exposed port or change port number mappings/names etc.
