### ISSUE TITLE
[Task] Machine-processable automated analysis results endpoint

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#880]
Depends on https://github.com/cryostatio/cryostat-core/issues/128

The machine-processable automated analysis results should be exposed in the HTTP API as an endpoint's JSON response.

**Comment by maxcao13** [comment]
Is it better to make new classes like `[Target]ReportEvalGetHandler` and do that or to add some option in the existing handlers if returning JSON, (as as form, path, or query) in the old v2 `[Target]ReportGetHandler`s?

**Comment by maxcao13** [comment]
When do I know if I should update the v1 vs. v2 handlers or both? In my mind, this is a newer feature so it would make more sense to just update the v2 ReportGetHandler and leave the v1 version as an older version however I notice that that v2 version is not documented in the HTTP API yet.

**Comment by andrewazores** [comment]
> When do I know if I should update the v1 vs. v2 handlers or both?

I guess that kind of decision falls on me :-)

In the case of the JWT-consuming V2 handlers, those are the ones primarily used by the web-client, and their V1 equivalents would still be preferred for programmatic clients. So for this feature, both should be updated.

> I notice that that v2 version is not documented in the HTTP API yet.

Ah...

Yea, that's something else that should be fixed.

**Comment by maxcao13** [comment]
I'm looking at [vert.x docs ](https://vertx.io/docs/vertx-web/java/#_routing_based_on_mime_types_acceptable_by_the_client)and I see that the way they do produces and consumes is by using the route. 

The code is what I tried in the `ReportGetHandler` but I don't think it works like that.
`
        ctx.currentRoute().produces("application/json").produces("text/html");
        String acceptableContentType = ctx.getAcceptableContentType();
`
I've also tried just manually parsing the `ctx.headers.accept()` but I'm not sure if there is a cleaner way to do this directly in each handler.

So should I be changing stuff in [WebServer.java ](https://github.com/maxcao13/cryostat/blob/main/src/main/java/io/cryostat/net/web/WebServer.java) then? Like changing the specific routes `[Target]ReportGetHandler` to produce both `application/json` and `text/html`?

**Comment by maxcao13** [comment]
If a client adds a header "Accept: image/webp" but the `[Target]ReportGetHandler` doesn't accept this type, what should happen? Right now it is simply returning a 404 HTTP Error message, but I'm wondering if a bad accept should just return the default content (html), as this is what most websites do (though I realize this endpoint is not a website).

If so, then should a bad Accept header like "Accept: ..." be accepted as well? As of right now, this produces a null getAcceptableContentType so I just null check and default to return HTML.

**Comment by andrewazores** [comment]
Adding path-specific behaviours to the `WebServer` is not desirable. The `RequestHandler` system we have is an abstraction designed specifically so that the `WebServer` class is as generic as possible and all of the route-specific behaviour is extracted into smaller units, like the `TargetReportGetHandler` class.

For an API v1 handler, I think you want to use some pattern like this:

```java
        String accept = ctx.request().headers().get(HttpHeaders.ACCEPT);
        switch (accept) {
            case "text/html":
                break;
            case "application/json":
                break;
            default:
                throw new HttpException(406);
        }
```

The piece that you found (`ctx.getAcceptableContentType()` and `route.produces()`) looks nice, but that's a wider change that should be applied to all of our `RequestHandler`s and handled generically by the `WebServer` that way. I think that's a little out of scope of this PR, but it could be a nice refactoring to perform later on. For now it's only really this endpoint where we are making use of the `Accept` header, so you can use a pattern like my snippet above to get around the problem for now.

**Comment by maxcao13** [comment]
Okay oneeee more problem sorry. What should be done in terms of the caching and such for returning the JSON?

Right now the ReportService is being called from each HTTP handler and goes straight to the Archived or Active cache to obtain the HTML Report as a String and it uses a RecordingDescriptor key to get them from the cache. 

But if we use the same thing for the JSON as a String, technically its the same RecordingDescriptor and everything since its the same JFR file but the cache output would be HTML instead of of JSON so a key would map to multiple values.

Should we be outputting a Pair of both the HTML and the JSON then? I think that would be a waste of resources to call 2 API calls if the caller only wants one dataform. Or maybe I don't use the ReportService at all and bypass caching altogether. Or maybe 2 caches... I'm not sure, what do you think is the best idea here?
