### ISSUE TITLE
Build fails if NPM not installed

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat#907]
I believe the cause of this is adding `npm run test` to the build script. Can we either install npm as well with frontend-maven-plugin, or run the tests with Yarn?

```
[INFO] webpack 5.55.1 compiled with 3 warnings in 23498 ms
[INFO] /bin/sh: npm: command not found
[INFO] error Command failed with exit code 127.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:55 min
[INFO] Finished at: 2022-04-26T14:49:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:yarn (yarn run build) on project cryostat: Failed to run task: 'yarn run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
```

**Comment by andrewazores** [comment]
Oh, yikes. `npm`/`node`/`yarn` are all installed by the `frontend-maven-plugin`, but in the web-client submodule's `package.json` it does an `npm run test` which ends up trying to run `npm` from the `$PATH`, and it isn't there with the way the frontend-maven-plugin is set up.

Easiest thing to do is probably split the tasks up within the `pom.xml`, unless there's a nice way to add the binaries that the frontend plugin downloads into the PATH, assuming it ends up forking a subprocess.
