### ISSUE TITLE
[Task] Report continues to show incomplete results after recording stops

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat#921]
It seems like the report for a running recording is not updated after the recording stops.

Example of `quarkus-test` sample app, 120s recording, ALL template. Recording stopped, but the report was initially generated while recording was running:
![Screenshot 2022-05-04 at 15-46-40 Recordings](https://user-images.githubusercontent.com/4326090/166815145-a69a3a03-f36c-4621-9972-63b465bc5800.png)

After archiving the recording, this also matches the report generated by downloading the JFR file and opening in JMC:
![Screenshot 2022-05-04 at 15-50-44 Recordings](https://user-images.githubusercontent.com/4326090/166815373-bff4829f-ec85-4421-b2ec-f737a0ef5056.png)

The "GC Caused by Heap Inspection" score increases, with the description going from 2 GCs to 4 GCs.

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/blob/main/src/main/java/io/cryostat/net/reports/ActiveRecordingReportCache.java

Reports for active recordings are cached by this class. It doesn't monitor for the `RUNNING -> STOPPED` recording state change, only the timestamp of the last report that was generated for a given recording.

**Comment by andrewazores** [comment]
I think when the `RUNNING -> STOPPED` recording state changes we should simply invalidate the report cache entry so that the report can be re-generated immediately the next time it is requested, since we know that the source data will no longer change later but is likely to have changed since the last time a report was generated. We do have an internal implicit recording stoppage notification that we emit, so we could just listen for that event from ourselves and invalidate the cache entry.

**Comment by andrewazores** [comment]
@maxcao13 I see you've self-assigned this.

> We do have an internal implicit recording stoppage notification that we emit, so we could just listen for that event from ourselves and invalidate the cache entry.

Currently in the backend we don't actually have any way to listen for notifications being emitted, so you'll have to add something to catch those and some way to hook into them internally.

I suggest using the Vert.x EventBus:

https://vertx.io/docs/vertx-core/java/#event_bus

https://vertx.io/docs/apidocs/io/vertx/core/eventbus/EventBus.html

The "address" for a message seems to correspond well with our notification categories, and the message with the notification body.

The existing `NotificationFactory` system can be used for publishing to the EventBus. You could then add a thin wrapper like `NotiifcationListener` that just abstracts around the EventBus on the subscription side (very much like the `-web` `NotificationChannel` service and its `.messages` function) so you can connect the report cache to the notification stream.

**Comment by maxcao13** [comment]
Hmm... okay I will look into the Event bus and how to use it for this. Thanks! ^^
