### ISSUE TITLE
[Story] Automated Analysis Scores in Dashboard

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#946]
Parent https://github.com/cryostatio/cryostat/issues/945

There should be an at-a-glance view for Automated Analysis reports scores embeddable in the cryostat-web Dashboard view. Rather than using the JMC-generated full-fledged HTML rules report, this should display as some more Patternfly-compliant components like Chips or Labels. N/A or green scores should not be included. This would provide users with a quick way to determine if there are any automatically detected performance issues on their application, without needing to select a specific recording and expand the table row to view the report document.

To facilitate this, Cryostat should simply take a snapshot recording of the selected target and then perform a rules report analysis on that snapshot. If there are no source recordings then no analysis is performed and some empty state content is displayed instead of scores indicators.

Tasks:
- [x] https://github.com/cryostatio/cryostat/issues/880
- [x] https://github.com/cryostatio/cryostat-reports/issues/23
- [x] https://github.com/cryostatio/cryostat/issues/918
- [x] https://github.com/cryostatio/cryostat-reports/issues/28
- [x] https://github.com/cryostatio/cryostat-core/issues/136
- [x] https://github.com/cryostatio/cryostat-web/issues/608

**Comment by maxcao13** [comment]
Anything else for this story?

**Comment by andrewazores** [comment]
Looks done.
